### ISSUE TITLE
Ability to provide a profile

### ISSUE THREAD

**Issue by FujiwaraChoki** [wkaisertexas/tiktok-uploader#100]
Would it be possible to implement a feature, to provide the path to a profile where I'm logged into TikTok already?

If I remember correctly, `selenium==4.9.0` supports this.

This is how I implemented it in my own project:

```python
    # Instantiate Firefox Options
    options = Options()

    # Bypass the bug in Selenium using this method
    # More Information: https://github.com/SeleniumHQ/selenium/issues/11028
    options.add_argument("-profile")
    options.add_argument(firefox_profile_location)

    # Instantiate Firefox Service
    service = Service(GECKODRIVER_PATH)

    # Instantiate Firefox Driver
    driver = webdriver.Firefox(service=service, options=options)
```

**Comment by paulvl** [comment]
@FujiwaraChoki you can use cookie_list based on your profile cookies. Please check the Authentication section on the documentation.

**Comment by FujiwaraChoki** [comment]
I understand, however, I was thinking for some users this may be faster.

Overall just optimization, not required for this app to be functional.

Also thanks for this!
