### ISSUE TITLE
no work

### ISSUE THREAD

**Issue by yasgomesvaz** [wkaisertexas/tiktok-uploader#101]
[19:48:38] Message: stale element reference: stale element not found
  (Session info: chrome=120.0.6099.225); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#stale-element-reference-exception
Stacktrace:
        GetHandleVerifier [0x00DA6EE3+174339]
        (No symbol) [0x00CD0A51]
        (No symbol) [0x009E6FF6]
        (No symbol) [0x009EAEAC]
        (No symbol) [0x009EC585]
        (No symbol) [0x009EC622]
        (No symbol) [0x00A1E380]
        (No symbol) [0x00A1D09E]
        (No symbol) [0x00A1B5F8]
        (No symbol) [0x00A1AD7F]
        (No symbol) [0x00A12B4E]
        (No symbol) [0x00A3700C]
        (No symbol) [0x00A125B0]
        (No symbol) [0x00A37414]
        (No symbol) [0x00A4A104]
        (No symbol) [0x00A36DA6]
        (No symbol) [0x00A11034]
        (No symbol) [0x00A11F8D]
        GetHandleVerifier [0x00E44B1C+820540]
        sqlite3_dbdata_init [0x00F053EE+653550]
        sqlite3_dbdata_init [0x00F04E09+652041]
        sqlite3_dbdata_init [0x00EF97CC+605388]
        sqlite3_dbdata_init [0x00F05D9B+656027]
        (No symbol) [0x00CDFE6C]
        (No symbol) [0x00CD83B8]
        (No symbol) [0x00CD84DD]
        (No symbol) [0x00CC5818]
        BaseThreadInitThunk [0x777EFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77E57C6E+286]
        RtlGetAppContainerNamedObjectPath [0x77E57C3E+238]

**Comment by fuzifim** [comment]
I think add more `time.sleep(config['implicit_wait'])` to `def complete_upload_form` in `upload.py` 
`_go_to_upload(driver)
    time.sleep(config['implicit_wait'])
    #  _remove_cookies_window(driver)
    _set_video(driver, path=path, **kwargs)
    time.sleep(config['implicit_wait'])
    _remove_split_window(driver)
    time.sleep(config['implicit_wait'])
    _set_interactivity(driver, **kwargs)
    time.sleep(config['implicit_wait'])
    _set_description(driver, description)
    time.sleep(config['implicit_wait'])
    if schedule:
        _set_schedule_video(driver, schedule)
    _post_video(driver)` 

:slightly_smiling_face:

**Comment by yasgomesvaz** [comment]
C:\Users\Gato\Desktop\tiktok>py tiktok.py
[14:10:54] ←[92mAuthenticating browser with cookies←[0m
[14:10:54] Uploading 204 videos
[14:10:54] Create a chrome browser instance

DevTools listening on ws://127.0.0.1:49924/devtools/browser/b8019755-7c8f-463d-bdc3-8e948ad1eb56
[14:10:57] Authenticating browser with cookies
[14:10:59] Posting C:\Users\Gato\Downloads\maa.nunes_\baurushoppingoficial - Cc_czxxLUpp.mp4
               with description: #fyp #fypppp #foryou #foryouuu #viral #viralvideo #fyyy
[14:10:59] Navigating to upload page
[14:11:08] Uploading video file
Message:
Stacktrace:
        GetHandleVerifier [0x009DE123+48179]
        (No symbol) [0x00965D01]
        (No symbol) [0x0084D72D]
        (No symbol) [0x0088572B]
        (No symbol) [0x0088586B]
        (No symbol) [0x008BC5B2]
        (No symbol) [0x008A3CD4]
        (No symbol) [0x008BAA1E]
        (No symbol) [0x008A3A26]
        (No symbol) [0x0087B7BC]
        (No symbol) [0x0087C62D]
        GetHandleVerifier [0x00CF7C33+3299139]
        GetHandleVerifier [0x00D35BF2+3553026]
        GetHandleVerifier [0x00D30BCC+3532508]
        GetHandleVerifier [0x00A7494E+664670]
        (No symbol) [0x00970AB4]
        (No symbol) [0x0096BF08]
        (No symbol) [0x0096C02D]
        (No symbol) [0x0095DD00]
        BaseThreadInitThunk [0x7736FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77A27C5E+286]
        RtlGetAppContainerNamedObjectPath [0x77A27C2E+238]

[14:12:13] Failed to upload C:\Users\Gato\Downloads\maa.nunes_\baurushoppingoficial - Cc_czxxLUpp.mp4
[14:12:13]
    A video failed to upload

[14:12:13] Posting C:\Users\Gato\Downloads\maa.nunes_\baurushoppingoficial - CdOfTAXNzmW.mp4
               with description: #fyp #fypppp #foryou #foryouuu #viral #viralvideo #fyyy
[14:12:13] Navigating to upload page



I have already made this change and it continues to give this error.
