### ISSUE TITLE
GetHandleVerifier [0x00CA6EE3+174339]

### ISSUE THREAD

**Issue by romanrsr** [wkaisertexas/tiktok-uploader#102]
(Using chrome 120.0.6099.225)

Message:
Stacktrace:
        GetHandleVerifier [0x00CA6EE3+174339]
        (No symbol) [0x00BD0A51]
        (No symbol) [0x008E6FF6]
        (No symbol) [0x00919876]
        (No symbol) [0x00919C2C]
        (No symbol) [0x0094BD42]
        (No symbol) [0x00937054]
        (No symbol) [0x0094A104]
        (No symbol) [0x00936DA6]
        (No symbol) [0x00911034]
        (No symbol) [0x00911F8D]
        GetHandleVerifier [0x00D44B1C+820540]
        sqlite3_dbdata_init [0x00E053EE+653550]
        sqlite3_dbdata_init [0x00E04E09+652041]
        sqlite3_dbdata_init [0x00DF97CC+605388]
        sqlite3_dbdata_init [0x00E05D9B+656027]
        (No symbol) [0x00BDFE6C]
        (No symbol) [0x00BD83B8]
        (No symbol) [0x00BD84DD]
        (No symbol) [0x00BC5818]
        BaseThreadInitThunk [0x75F46A39+25]
        RtlGetFullPathName_UEx [0x76EC7F8D+173]
        RtlGetFullPathName_UEx [0x76EC7F5B+123]

**Comment by byStayo** [comment]
same

**Comment by noahlom** [comment]
I fixed this by running it non headless, but when the video uploads it gets stuck

**Comment by romanrsr** [comment]
> i fixed it by removing the following lines in upload.py
> 
> ```
>             # wait until a non-draggable image is found
>             process_confirmation = EC.presence_of_element_located(
>                 (By.XPATH, config['selectors']['upload']['process_confirmation'])
>                 )
>             WebDriverWait(driver, config['explicit_wait']).until(process_confirmation)
> ```

What fork are u using?

**Comment by drjajas** [comment]
im not sure what you mean. i installed the latest version by using: pip install tiktok-uploader

**Comment by dyPlet** [comment]
Oh I have also removed those lines, in my PR. Maybe it will get removed if that is useless. Let's see
