### ISSUE TITLE
Redirects to the login page

### ISSUE THREAD

**Issue by yablochnyi** [wkaisertexas/tiktok-uploader#103]
I am constantly redirected to the login page, am I doing something wrong? added only value
`
def upload_tiktok(film_data):
    cookies_list = [
        {
            'name': 'sessionid',
            'value': '650333bbe17gdrslk7658a66777a89a9b677f',
            'domain': '.tiktok.com',
            'path': '/',
            'expiry': '30/01/2024, 18:37:59 PM'
        }
    ]
    video_path = film_data.video
    description = film_data.description

    upload_video(video_path, description=description, cookies_list=cookies_list)
`

**Comment by wkaisertexas** [comment]
Use `cookies.txt` which is the format for **each** cookie. I will make a better note of that, but you need more than you sesionid to get authentication to work properly.

**Comment by yablochnyi** [comment]
> Use `cookies.txt` which is the format for **each** cookie. I will make a better note of that, but you need more than you sesionid to get authentication to work properly.

Thanks for pointing out the problem)
I haven't worked with python yet, it's hard to grasp everything.
Now I get another error, I see that the video is loading, but there is an error at the end
`
[21:27:40] Failed to upload D:\Python\tiktok\public\films\test\test.mp4
[21:27:40] 
    A video failed to upload
    
Message: 
Stacktrace:
	GetHandleVerifier [0x00DB6EE3+174339]
	(No symbol) [0x00CE0A51]
	(No symbol) [0x009F6FF6]
	(No symbol) [0x00A29876]
	(No symbol) [0x00A29C2C]
	(No symbol) [0x00A5BD42]
	(No symbol) [0x00A47054]
	(No symbol) [0x00A5A104]
	(No symbol) [0x00A46DA6]
	(No symbol) [0x00A21034]
	(No symbol) [0x00A21F8D]
	GetHandleVerifier [0x00E54B1C+820540]
	sqlite3_dbdata_init [0x00F153EE+653550]
	sqlite3_dbdata_init [0x00F14E09+652041]
	sqlite3_dbdata_init [0x00F097CC+605388]
	sqlite3_dbdata_init [0x00F15D9B+656027]
	(No symbol) [0x00CEFE6C]
	(No symbol) [0x00CE83B8]
	(No symbol) [0x00CE84DD]
	(No symbol) [0x00CD5818]
	BaseThreadInitThunk [0x75857BA9+25]
	RtlInitializeExceptionChain [0x771FBD2B+107]
	RtlClearBits [0x771FBCAF+191]

`
