### ISSUE TITLE
A video failed to upload

### ISSUE THREAD

**Issue by oskardel** [wkaisertexas/tiktok-uploader#107]
I'm trying to post some videos with the upload_videos function but for some reason, Selenium stops at the "Split into multiple parts to get more exposure" TikTok window and after a while this error appears:

Message: 
Stacktrace:
        GetHandleVerifier [0x00007FF7DF005E42+3538674]
        (No symbol) [0x00007FF7DEC24C02]
        (No symbol) [0x00007FF7DEAD5AEB]
        (No symbol) [0x00007FF7DEB1BF4E]
        (No symbol) [0x00007FF7DEB1C0CC]
        (No symbol) [0x00007FF7DEB5E477]
        (No symbol) [0x00007FF7DEB3F0EF]
        (No symbol) [0x00007FF7DEB5BDE3]
        (No symbol) [0x00007FF7DEB3EE53]
        (No symbol) [0x00007FF7DEB0F514]
        (No symbol) [0x00007FF7DEB10631]
        GetHandleVerifier [0x00007FF7DF036CAD+3738973]
        GetHandleVerifier [0x00007FF7DF08C506+4089270]
        GetHandleVerifier [0x00007FF7DF084823+4057299]
        GetHandleVerifier [0x00007FF7DED55C49+720121]
        (No symbol) [0x00007FF7DEC3126F]
        (No symbol) [0x00007FF7DEC2C304]
        (No symbol) [0x00007FF7DEC2C432]
        (No symbol) [0x00007FF7DEC1BD04]
        BaseThreadInitThunk [0x00007FFAE12A257D+29]
        RtlUserThreadStart [0x00007FFAE16CAA58+40]

[13:15:57] Failed to upload D:\python-automation\media\processed_videos\0-31show.mp4
[13:15:57] A video failed to upload

This of course happens with all videos and it skips the upload. Somebody help please.

**Comment by SpartacusIV** [comment]
Same problem

**Comment by AkramHamd** [comment]
Did you solved this one? For what I see I think tiktok changed his layout and buttons doesn't match with the code
