### ISSUE TITLE
add netscape\json cookies format

### ISSUE THREAD

**Issue by zerofishy** [wkaisertexas/tiktok-uploader#111]
can  you add netscape\json format for video upload?from .txt

**Comment by wkaisertexas** [comment]
The `.txt` file created by `get_cookies.txt` is in the Netscape cookie format. 

Alternatively, you are allowed to pass a dictionary of cookies. [(see README)](https://github.com/wkaisertexas/tiktok-uploader#--authentication)

To parse your JSON into a dictionary, you can use the following snippet:

```python
from json import load

with open("my_file.json") as f:
   cookies_dict = json.load(f)
```
