### ISSUE TITLE
No Work

### ISSUE THREAD

**Issue by yasgomesvaz** [wkaisertexas/tiktok-uploader#112]
C:\Users\Gato\Desktop\tiktok>py tiktok.py
[14:10:54] ←[92mAuthenticating browser with cookies←[0m
[14:10:54] Uploading 204 videos
[14:10:54] Create a chrome browser instance

DevTools listening on ws://127.0.0.1:49924/devtools/browser/b8019755-7c8f-463d-bdc3-8e948ad1eb56
[14:10:57] Authenticating browser with cookies
[14:10:59] Posting C:\Users\Gato\Downloads\maa.nunes_\baurushoppingoficial - Cc_czxxLUpp.mp4
with description: #fyp #fypppp #foryou #foryouuu #viral #viralvideo #fyyy
[14:10:59] Navigating to upload page
[14:11:08] Uploading video file
Message:
Stacktrace:
GetHandleVerifier [0x009DE123+48179]
(No symbol) [0x00965D01]
(No symbol) [0x0084D72D]
(No symbol) [0x0088572B]
(No symbol) [0x0088586B]
(No symbol) [0x008BC5B2]
(No symbol) [0x008A3CD4]
(No symbol) [0x008BAA1E]
(No symbol) [0x008A3A26]
(No symbol) [0x0087B7BC]
(No symbol) [0x0087C62D]
GetHandleVerifier [0x00CF7C33+3299139]
GetHandleVerifier [0x00D35BF2+3553026]
GetHandleVerifier [0x00D30BCC+3532508]
GetHandleVerifier [0x00A7494E+664670]
(No symbol) [0x00970AB4]
(No symbol) [0x0096BF08]
(No symbol) [0x0096C02D]
(No symbol) [0x0095DD00]
BaseThreadInitThunk [0x7736FCC9+25]
RtlGetAppContainerNamedObjectPath [0x77A27C5E+286]
RtlGetAppContainerNamedObjectPath [0x77A27C2E+238]

[14:12:13] Failed to upload C:\Users\Gato\Downloads\maa.nunes_\baurushoppingoficial - Cc_czxxLUpp.mp4
[14:12:13]
A video failed to upload

[14:12:13] Posting C:\Users\Gato\Downloads\maa.nunes_\baurushoppingoficial - CdOfTAXNzmW.mp4
with description: #fyp #fypppp #foryou #foryouuu #viral #viralvideo #fyyy
[14:12:13] Navigating to upload page

I have already made this change and it continues to give this error.

**Comment by yasgomesvaz** [comment]
New error
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:509:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

**Comment by dyPlet** [comment]
Indeed, looks like a new error occurred that I had not before. I will investigate

**Comment by dyPlet** [comment]
I have fixed the error related to the schedule in my fork

**Comment by dyPlet** [comment]
> Indeed, looks like a new error occurred that I had not before. I will investigate

Update: I don't have this error on my fork, I thought I had it but it was something else

**Comment by yasgomesvaz** [comment]
> > Na verdade, parece que ocorreu um novo erro que eu não tinha antes. Eu investigarei
> 
> Atualização: não tenho esse erro no meu fork, pensei que tinha, mas era outra coisa

C:\Users\Gato\Desktop\tiktok>py tiktok.py
[20:32:40] ←[92mAuthenticating browser with cookies←[0m
[20:32:40] Uploading 204 videos
[20:32:40] Create a firefox browser instance
[20:32:54] Authenticating browser with cookies
[20:32:55] Posting C:\Users\Gato\Downloads\maa.nunes_\baurushoppingoficial - Cc_czxxLUpp.mp4
               with description: #fyp #fypppp #foryou #foryouuu #viral #viralvideo #fyyy
[20:32:55] Navigating to upload page
[20:32:57] Uploading video file
[20:33:05] Removing split window
[20:33:10] Split window not found or operation timed out
[20:33:10] Setting interactivity settings
[20:33:15] Failed to set interactivity settings
[20:33:15] Setting description
[20:33:56] Clicking the post button
[20:34:57] Failed to upload C:\Users\Gato\Downloads\maa.nunes_\baurushoppingoficial - Cc_czxxLUpp.mp4
[20:34:57] Message:
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:191:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:509:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

[20:34:57] Posting C:\Users\Gato\Downloads\maa.nunes_\baurushoppingoficial - CdOfTAXNzmW.mp4
               with description: #fyp #fypppp #foryou #foryouuu #viral #viralvideo #fyyy
[20:34:57] Navigating to upload page

When using your library I get this error

**Comment by lugor2016** [comment]
> C:\Users\Gato\Desktop\tiktok>py tiktok.py [14:10:54] ←[92mAuthenticating browser with cookies←[0m [14:10:54] Uploading 204 videos [14:10:54] Create a chrome browser instance
> 
> DevTools listening on ws://127.0.0.1:49924/devtools/browser/b8019755-7c8f-463d-bdc3-8e948ad1eb56 [14:10:57] Authenticating browser with cookies [14:10:59] Posting C:\Users\Gato\Downloads\maa.nunes_\baurushoppingoficial - Cc_czxxLUpp.mp4 with description: #fyp #fypppp #foryou #foryouuu #viral #viralvideo #fyyy [14:10:59] Navigating to upload page [14:11:08] Uploading video file Message: Stacktrace: GetHandleVerifier [0x009DE123+48179] (No symbol) [0x00965D01] (No symbol) [0x0084D72D] (No symbol) [0x0088572B] (No symbol) [0x0088586B] (No symbol) [0x008BC5B2] (No symbol) [0x008A3CD4] (No symbol) [0x008BAA1E] (No symbol) [0x008A3A26] (No symbol) [0x0087B7BC] (No symbol) [0x0087C62D] GetHandleVerifier [0x00CF7C33+3299139] GetHandleVerifier [0x00D35BF2+3553026] GetHandleVerifier [0x00D30BCC+3532508] GetHandleVerifier [0x00A7494E+664670] (No symbol) [0x00970AB4] (No symbol) [0x0096BF08] (No symbol) [0x0096C02D] (No symbol) [0x0095DD00] BaseThreadInitThunk [0x7736FCC9+25] RtlGetAppContainerNamedObjectPath [0x77A27C5E+286] RtlGetAppContainerNamedObjectPath [0x77A27C2E+238]
> 
> [14:12:13] Failed to upload C:\Users\Gato\Downloads\maa.nunes_\baurushoppingoficial - Cc_czxxLUpp.mp4 [14:12:13] A video failed to upload
> 
> [14:12:13] Posting C:\Users\Gato\Downloads\maa.nunes_\baurushoppingoficial - CdOfTAXNzmW.mp4 with description: #fyp #fypppp #foryou #foryouuu #viral #viralvideo #fyyy [14:12:13] Navigating to upload page
> 
> I have already made this change and it continues to give this error.

i have several tiktok channels where i upload video using this python library, only on two it shows me this error, others work normally...
