### ISSUE TITLE
Tiktok just changed their publish interface, and the automation stopped working...

### ISSUE THREAD

**Issue by felipexpert** [wkaisertexas/tiktok-uploader#122]
The new publishing tiktok interface has changed, this script is no longer working, please, who created this great tool, make it work again

**Comment by joaovit1** [comment]
Mine stopped working today too, checked a few paths, 

My code was working even with the error mentioned in #116, now it is failing without any errors

It uploads the video and is not detecting the video was uploaded, not sure if the "title" being searched in here:

`upload_confirmation = "//div[@title]"`

Is the same as I changed to:

`upload_confirmation = "//div[contains(@class, 'info-title')]"`

However now it is detecting the video was uploaded, now there are problems with the paths when setting the hashtags, scheduling and maybe posting too

**Comment by callum-fortune** [comment]
joaovit1 is correct here in that a selector (`post_confirmation`) needs changing to match the new text in the TikTok UI. This has been addressed in my PR (https://github.com/wkaisertexas/tiktok-uploader/pull/125).

Hopefully that solves your issue.
