### ISSUE TITLE
"A video failed to upload"

### ISSUE THREAD

**Issue by Jamadoo** [wkaisertexas/tiktok-uploader#126]
I installed the lib on my cmd using pip, and wanted to use it as a CLI program. I used the following command:
tiktok-uploader -v video.mp4 -d "this is a text" -c cookies.txt
Ensuring all the files exist and are valid. The cookies txt file as well

**I get the following output:**
```
[21:00:49] ←[92mAuthenticating browser with cookies←[0m
[21:00:49] Create a chrome browser instance in headless mode

DevTools listening on ws://127.0.0.1:31540/devtools/browser/60992497-6c0d-4010-86f8-67ff75001fab
[21:00:53] Authenticating browser with cookies
[21:00:57] Posting video.mp4
               with description: this is a text
[21:00:57] Navigating to upload page
[23008:2960:0419/210057.638:ERROR:cert_issuer_source_aia.cc(35)] Error parsing cert retrieved from AIA (as DER):
ERROR: Couldn't read tbsCertificate as SEQUENCE
ERROR: Failed parsing Certificate

[21:01:00] Uploading video file
Message:
Stacktrace:
        GetHandleVerifier [0x00724CA3+225091]
        (No symbol) [0x00654DF1]
        (No symbol) [0x004F9A7A]
        (No symbol) [0x0053175B]
        (No symbol) [0x0053188B]
        (No symbol) [0x00567882]
        (No symbol) [0x0054F5A4]
        (No symbol) [0x00565CB0]
        (No symbol) [0x0054F2F6]
        (No symbol) [0x005279B9]
        (No symbol) [0x0052879D]
        sqlite3_dbdata_init [0x00B99A43+4064547]
        sqlite3_dbdata_init [0x00BA104A+4094762]
        sqlite3_dbdata_init [0x00B9B948+4072488]
        sqlite3_dbdata_init [0x0089C9A9+930953]
        (No symbol) [0x006607C4]
        (No symbol) [0x0065ACE8]
        (No symbol) [0x0065AE11]
        (No symbol) [0x0064CA80]
        BaseThreadInitThunk [0x76E0FEF9+25]
        RtlGetAppContainerNamedObjectPath [0x777D7BBE+286]
        RtlGetAppContainerNamedObjectPath [0x777D7B8E+238]

[21:02:05] Failed to upload [removed for privacy]
[21:02:05]
    A video failed to upload

-------------------------
Error while uploading video
-------------------------
```

Im guessing this has something to do with the tiktok site and the script not finding an element while navigating to the upload page?

On a Windows 10 Pro Computer
Ryzen 5300U with integrated graphics

**Comment by wkaisertexas** [comment]
Try to install by cloning the git repository directly. There was a PR made recently #125 which should have fixed this.

**Comment by Jamadoo** [comment]
Added the latest github repo to my project, video gets uploaded but script gets stuck in a wait loop waiting for...something. Im debugging now

**Comment by callum-fortune** [comment]
@Jamadoo Just to confirm what command are you running? When I run the basic_upload.py script, it seems to work without issue so I'll try with whatever script/command you're using...

**Comment by yellow-cmd** [comment]
Hey! I am having the same problem with the `upload_video`, when it reaches the upload page it just get stuck and won't do nothing. I've tried doing pip installing again but it seems that the issue is still there, any ideas?

**Comment by Jamadoo** [comment]
> @Jamadoo Just to confirm what command are you running? When I run the basic_upload.py script, it seems to work without issue so I'll try with whatever script/command you're using...

I fixed the issue. It was a personal mistake. I forgot to uninstall the package, thus my python still used the pip library instead of the imported git repo. Upload script works perfectly with the new repo
