### ISSUE TITLE
Caption Set To "Posted a Video" When Posting In Headless Mode

### ISSUE THREAD

**Issue by Jamadoo** [wkaisertexas/tiktok-uploader#129]
There is no errors in the console and the "_set_interactivity" and "_set_description" function does get fired. When I run the script in normal mode, my caption gets typed and added to the video. But when I run it in headless mode, it fails to set my custom caption and sets it as "Posted a Video".

The console outputs exactly what is expected with no errors.

I have not rested if this gets resolved by using different browsers. 

If any other information is needed, just ask.

**Comment by callum-fortune** [comment]
@Jamadoo I have submitted a new PR to deal with the description, check out the fork on my profile under the hashtag branch and let me know if the issue persists....
