### ISSUE TITLE
Failed to upload

### ISSUE THREAD

**Issue by danielrousseaug** [wkaisertexas/tiktok-uploader#132]
Hello, the uploader is failing and I'm unsure why:

[16:15:47] Authenticating browser with cookies
[16:15:49] Posting output_86.mp4
               with description: something to think about... #wisewords #poetry #3amthoughts
[16:15:49] Navigating to upload page
[16:15:51] Uploading video file
[25784:49416:0426/161559.424:ERROR:device_event_log_impl.cc(195)] [16:15:59.423] USB: usb_service_win.cc:105 SetupDiGetDeviceProperty({{A45C254E-DF1C-4EFD-8020-67D146A850E0}, 6}) failed: Element not found. (0x490)
Created TensorFlow Lite XNNPACK delegate for CPU.
Message:
Stacktrace:
        GetHandleVerifier [0x0074C113+48259]
        (No symbol) [0x006DCA41]
        (No symbol) [0x005D0A17]
        (No symbol) [0x00610BED]
        (No symbol) [0x00610C9B]
        (No symbol) [0x0064BC12]
        (No symbol) [0x00630DE4]
        (No symbol) [0x00649B9C]
        (No symbol) [0x00630B36]
        (No symbol) [0x0060570D]
        (No symbol) [0x006062CD]
        GetHandleVerifier [0x00A06533+2908323]
        GetHandleVerifier [0x00A43B4B+3159739]
        GetHandleVerifier [0x007E505B+674763]
        GetHandleVerifier [0x007EB21C+699788]
        (No symbol) [0x006E6244]
        (No symbol) [0x006E2298]
        (No symbol) [0x006E242C]
        (No symbol) [0x006D4BB0]
        BaseThreadInitThunk [0x77517BA9+25]
        RtlInitializeExceptionChain [0x77C5BD2B+107]
        RtlClearBits [0x77C5BCAF+191]

[16:16:54] Failed to upload C:\Users\danie\OneDrive\Desktop\output_86.mp4
[16:16:54]
    A video failed to upload

-------------------------
Error while uploading video
-------------------------

**Comment by danielrousseaug** [comment]
I've built from source and it now works, a bit odd to reccomend PyPI installation when you don't maintain it Mr. Kaiser

**Comment by wkaisertexas** [comment]
PyPI is recommended for most people because installing from source can be a pain.

I should be more efficient about pushing new builds however

**Comment by dsaderholm** [comment]
Hey, I'm getting this exact same issue and I built it from the source. Do you have any ideas?

**Comment by danielrousseaug** [comment]
> Hey, I'm getting this exact same issue and I built it from the source. Do you have any ideas?

I got the issue again today, I re-obtained my cookies and it worked after, might be an issue with tiktok resetting auth tokens or something? Thoughts @wkaisertexas

**Comment by dsaderholm** [comment]
> > Hey, I'm getting this exact same issue and I built it from the source. Do you have any ideas?
> 
> I got the issue again today, I re-obtained my cookies and it worked after, might be an issue with tiktok resetting auth tokens or something? Thoughts @wkaisertexas

That did fix it for me. For some reason, my hashtags aren't working now, but that is probably unrelated.
