### ISSUE TITLE
the video wont be uploaded 

### ISSUE THREAD

**Issue by aminoz1234** [wkaisertexas/tiktok-uploader#14]
so everything seems to be working perfectly the headless browser does everything right, the problem is after the video is finished uploading (reaches 100%) it closes the browser and the console says the video failed to upload. maybe the browser does not click on the publish button before closing ? some help here pls 
by the way there is no problem with the vid itself cause i did uploaded manually later on

**Comment by jocbrl** [comment]
Same problem, Plz we need help

**Comment by ethernalsteve** [comment]
It is important to pass the language to tiktak, because everything in the code is tied to English. The easiest way is to pass in a cookie:

.tiktok.com	TRUE	/	TRUE	1710021971	tiktok_webapp_lang	en

**Comment by sirducu** [comment]
i have the same problem, and I already passed in the lang cookie.

**Comment by labibmaromiibnu-cmd** [comment]
Wowowwwww
