### ISSUE TITLE
The application is great, can you add an option to select affiliate products?

### ISSUE THREAD

**Issue by KalvinThien** [wkaisertexas/tiktok-uploader#142]
The application is great, can you add an option to select affiliate products?

Like this 

![image](https://github.com/wkaisertexas/tiktok-uploader/assets/120565705/ae9e048e-ef6e-4b0e-b849-567207812ea4)
thanks

**Comment by wkaisertexas** [comment]
This is not currently something planned. The code is open source so you can always submit a pr for review.
