### ISSUE TITLE
Low views with uploader.

### ISSUE THREAD

**Issue by romanrsr** [wkaisertexas/tiktok-uploader#144]
Does it happen to anyone else that using the uploader you have few views? If I upload something manually with the same browser, IP and PC, I have almost 10 times more views than if I upload it with the uploader.

**Comment by tonysmiles** [comment]
> Does it happen to anyone else that using the uploader you have few views? If I upload something manually with the same browser, IP and PC, I have almost 10 times more views than if I upload it with the uploader.

Does the video have 0 views or over 100 views?

**Comment by romanrsr** [comment]
> > Does it happen to anyone else that using the uploader you have few views? If I upload something manually with the same browser, IP and PC, I have almost 10 times more views than if I upload it with the uploader.
> 
> Does the video have 0 views or over 100 views?

Those that I publish with uploader have less than 100, those that I publish manually have more than 1000.

**Comment by tonysmiles** [comment]
> > > Does it happen to anyone else that using the uploader you have few views? If I upload something manually with the same browser, IP and PC, I have almost 10 times more views than if I upload it with the uploader.
> > 
> > 
> > Does the video have 0 views or over 100 views?
> 
> Those that I publish with uploader have less than 100, those that I publish manually have more than 1000.
Do you use proxies?

**Comment by tonysmiles** [comment]
> > > Does it happen to anyone else that using the uploader you have few views? If I upload something manually with the same browser, IP and PC, I have almost 10 times more views than if I upload it with the uploader.
> > 
> > 
> > Does the video have 0 views or over 100 views?
> 
> Those that I publish with uploader have less than 100, those that I publish manually have more than 1000.

Do you use proxies?

**Comment by romanrsr** [comment]
> > > > Does it happen to anyone else that using the uploader you have few views? If I upload something manually with the same browser, IP and PC, I have almost 10 times more views than if I upload it with the uploader.
> > > 
> > > 
> > > Does the video have 0 views or over 100 views?
> > 
> > 
> > Those that I publish with uploader have less than 100, those that I publish manually have more than 1000.
> 
> Do you use proxies?

No, I use the same IP to publish them by the uploader and manually.

**Comment by romanrsr** [comment]
> The uploader is alone insufficient to avoid detection.

Thank you very much for the clarification! And what do you recommend?

**Comment by wkaisertexas** [comment]
It is going to take some testing on your part. It has been a while since I have looked more closely into this so I am not too sure what is correct to do now.
