### ISSUE TITLE
TikTok-Uploader Not Pressing Upload/ Error Uploading

### ISSUE THREAD

**Issue by AlexisRSM** [wkaisertexas/tiktok-uploader#147]
While it seems the script is running well, when it arrives to the final it is not able to click the Post button. Printing out that there was an error uploading the video. 

Setting interactivity settings
[01:50:27] Failed to set interactivity settings
[01:50:27] Setting description
[01:50:29] Clicking the post button
[01:51:30] Failed to upload

Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

**Comment by Crqical** [comment]
Having the exact same issue

**Comment by Crqical** [comment]
Everything is working except the button

**Comment by wdoer** [comment]
yes it's strange, the button class is the same but it doesn't work for me too today

**Comment by Lucid-0x** [comment]
> good working in new account, maybe limit

can you please tell me what did you do also side note what OS are you using to get it work

**Comment by wdoer** [comment]
> > good working in new account, maybe limit
> 
> can you please tell me what did you do also side note what OS are you using to get it work

checking in the same directory but with a different sessionid, now no longer have a problem on my main accounts
I guess it was a limit because really uploaded a lot, used macos sonoma

**Comment by AlexisRSM** [comment]
I am using W11 but still could not make it work still. It always crashes in the final part saying there was a problem with the upload, I turned off headless mode to see what was happening and the video and all the rest worked fine.
