### ISSUE TITLE
Error while uploading video

### ISSUE THREAD

**Issue by berndthiel** [wkaisertexas/tiktok-uploader#148]
Hi Team, i use this tool over my Powershell Engine,
since i uploaed successfully 3 videos since their it runs in error
I highlight the Errocodes in **BOLD**
Syntax i checked multiple times and works all correct,
but it failes after/in upload see LOG

Any Idea?

![image](https://github.com/wkaisertexas/tiktok-uploader/assets/26602041/4b52f750-f56f-49b0-841f-6795eb8df8b7)

![image](https://github.com/wkaisertexas/tiktok-uploader/assets/26602041/f8aa441a-b688-449d-ad76-d75a16b5946c)

**Comment by schieferzahn** [comment]
same problem here...
