### ISSUE TITLE
Solve the problem of 0 views

### ISSUE THREAD

**Issue by tonysmiles** [wkaisertexas/tiktok-uploader#149]
I need to discuss this issue to find a solution. Currently, I have two newly created accounts.
+ Account 1: I manually upload videos using Firefox Portable and it has viewers, specifically 500 views.
+ Account 2: I upload videos automatically using Chrome and it has no viewers, with 0 views.

I am currently suspecting that TikTok might have detected duplicate profiles between the browsers. Has anyone else experienced this issue? Please suggest possible solutions to resolve this problem.

**Comment by romanrsr** [comment]
Same here

**Comment by romanrsr** [comment]
At the moment the "Solution" that I have found is to run an account on each VM, but surely there is a more practical method.

**Comment by tonysmiles** [comment]
> At the moment the "Solution" that I have found is to run an account on each VM, but surely there is a more practical method.

If you apply this method, how many video views will there be?

**Comment by romanrsr** [comment]
> > At the moment the "Solution" that I have found is to run an account on each VM, but surely there is a more practical method.
> 
> If you apply this method, how many video views will there be?

It depends on each account. But all above 300. By the way, I saw in a PR that you were able to solve the schedule, is it still working for you?

**Comment by tonysmiles** [comment]
> > > At the moment the "Solution" that I have found is to run an account on each VM, but surely there is a more practical method.
> > 
> > 
> > If you apply this method, how many video views will there be?
> 
> It depends on each account. But all above 300. By the way, I saw in a PR that you were able to solve the schedule, is it still working for you?

I have scheduled a fixed schedule, but the number of views is still 0 views

**Comment by romanrsr** [comment]
Could you give me the scripts that you modified so that the schedule works for you?

**Comment by tonysmiles** [comment]
> Could you give me the scripts that you modified so that the schedule works for you?

try:
        try:
            # Thực hiện tìm kiếm và kích hoạt radio button bằng cách sử dụng selector
            radio_button = driver.find_element(By.CSS_SELECTOR, config['selectors']['schedule']['radio_button'])
            radio_button.click()
        except NoSuchElementException:
            # Xử lý nếu không tìm thấy phần tử
            switch = driver.find_element(By.XPATH, config['selectors']['schedule']['switch'])
            switch.click()
        __date_picker(driver, month, day)
        __time_picker(driver, hour, minute)
    except Exception as e:
        msg = f'Lỗi đặt lịch đăng: {e}'
        logger.error(red(msg))
        raise FailedToUpload()

**Comment by romanrsr** [comment]
That's in the config.toml right?

**Comment by L1mexCodder** [comment]
check shadow ban
