### ISSUE TITLE
works on linux console?

### ISSUE THREAD

**Issue by thebardockgames** [wkaisertexas/tiktok-uploader#15]
Can it be used on a console that uses linux? I currently use it to upload a video daily from a server that only uses a console and is a linux distribution but it gives me an error when executing it

**Comment by wkaisertexas** [comment]
Linux should work. I don't have access to my distro right now to test it, but both `selenium` and `webdrivermanager` explicitly support Linux (if you are using `FireFox` or `Chrome`).
