### ISSUE TITLE
IT doesn't post at the end (now works after an edit in the code)

### ISSUE THREAD

**Issue by Lucid-0x** [wkaisertexas/tiktok-uploader#150]
i got this error
![image](https://github.com/wkaisertexas/tiktok-uploader/assets/85033489/8af04eaa-f5f8-4537-ac96-ca97ed366df9)

I tried to change the post = "//div[contains(@class, 'btn-post')]" to everything else but all the same error 
I also tried it in firefox and it has a different upload interface then same error at the post
![image](https://github.com/wkaisertexas/tiktok-uploader/assets/85033489/827c0ac1-7d87-4a3b-8649-b81a53abef57)

also one thing I installed it from pip and last update was 24 April... will this make a difference 
also I tried on windows 10 and kali linux machine both same results

**Comment by Ducksss** [comment]
Same issue as you...

**Comment by AliceKawanami** [comment]
If you go over to the tiktok upload page and select the upload button with inspect element 
![image](https://github.com/wkaisertexas/tiktok-uploader/assets/97620755/ef73f461-abfd-4d6f-8020-fc38c0031a31)
You should see the button class.
![image](https://github.com/wkaisertexas/tiktok-uploader/assets/97620755/8d25a7d2-c131-4aee-85ba-4ac5c141f2f8)
change the upload class to that in the config.toml file

**Comment by Lucid-0x** [comment]
> If you go over to the tiktok upload page and select the upload button with inspect element (in the part pointed by the arrow) ![image](https://private-user-images.githubusercontent.com/97620755/334215024-ef73f461-abfd-4d6f-8020-fc38c0031a31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NzEwMzMsIm5iZiI6MTcxNjg3MDczMywicGF0aCI6Ii85NzYyMDc1NS8zMzQyMTUwMjQtZWY3M2Y0NjEtYWJmZC00ZDZmLTgwMjAtZmMzOGMwMDMxYTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA0MzIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwM2QzZGI1NWEyODNmZTZiZjgxZGIyYTI1ZTBjOTZlZDlmZTUzZThiZjdmYTAwYWE3MGFmMGZmZDBhM2I1NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GTe9PFDiVb4sd6UZCYpVqf-W1rA2O49mdZF9RTFzQfw) You should see the button class. ![image](https://private-user-images.githubusercontent.com/97620755/334215103-8d25a7d2-c131-4aee-85ba-4ac5c141f2f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NzEwMzMsIm5iZiI6MTcxNjg3MDczMywicGF0aCI6Ii85NzYyMDc1NS8zMzQyMTUxMDMtOGQyNWE3ZDItYzEzMS00YWVlLTg1YmEtNGFjNWMxNDFmMmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA0MzIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYWQwNTliOTA3YWJkYzZlMDQ2NDc2MjQyNTgwZjUyY2VkNTIxYTQ3NTEyYzA2YzNlNDBhNGNiNWJmMjAzMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bFBfUa8CQ4cKic-xDI0HTRn5eJkmE7JphLEuxS_Jp6Q) change the upload class to that in the config.toml file


I already tried that but thanks for the suggestion

**Comment by cslop3r** [comment]
> > If you go over to the tiktok upload page and select the upload button with inspect element (in the part pointed by the arrow) ![image](https://private-user-images.githubusercontent.com/97620755/334215024-ef73f461-abfd-4d6f-8020-fc38c0031a31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NzEwMzMsIm5iZiI6MTcxNjg3MDczMywicGF0aCI6Ii85NzYyMDc1NS8zMzQyMTUwMjQtZWY3M2Y0NjEtYWJmZC00ZDZmLTgwMjAtZmMzOGMwMDMxYTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA0MzIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwM2QzZGI1NWEyODNmZTZiZjgxZGIyYTI1ZTBjOTZlZDlmZTUzZThiZjdmYTAwYWE3MGFmMGZmZDBhM2I1NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GTe9PFDiVb4sd6UZCYpVqf-W1rA2O49mdZF9RTFzQfw) You should see the button class. ![image](https://private-user-images.githubusercontent.com/97620755/334215103-8d25a7d2-c131-4aee-85ba-4ac5c141f2f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NzEwMzMsIm5iZiI6MTcxNjg3MDczMywicGF0aCI6Ii85NzYyMDc1NS8zMzQyMTUxMDMtOGQyNWE3ZDItYzEzMS00YWVlLTg1YmEtNGFjNWMxNDFmMmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA0MzIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYWQwNTliOTA3YWJkYzZlMDQ2NDc2MjQyNTgwZjUyY2VkNTIxYTQ3NTEyYzA2YzNlNDBhNGNiNWJmMjAzMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bFBfUa8CQ4cKic-xDI0HTRn5eJkmE7JphLEuxS_Jp6Q) change the upload class to that in the config.toml file
> 
> I already tried that but thanks for the suggestion

Hi did you solve your issue?

**Comment by Lucid-0x** [comment]
> > > If you go over to the tiktok upload page and select the upload button with inspect element (in the part pointed by the arrow) ![image](https://private-user-images.githubusercontent.com/97620755/334215024-ef73f461-abfd-4d6f-8020-fc38c0031a31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NzEwMzMsIm5iZiI6MTcxNjg3MDczMywicGF0aCI6Ii85NzYyMDc1NS8zMzQyMTUwMjQtZWY3M2Y0NjEtYWJmZC00ZDZmLTgwMjAtZmMzOGMwMDMxYTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA0MzIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwM2QzZGI1NWEyODNmZTZiZjgxZGIyYTI1ZTBjOTZlZDlmZTUzZThiZjdmYTAwYWE3MGFmMGZmZDBhM2I1NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GTe9PFDiVb4sd6UZCYpVqf-W1rA2O49mdZF9RTFzQfw) You should see the button class. ![image](https://private-user-images.githubusercontent.com/97620755/334215103-8d25a7d2-c131-4aee-85ba-4ac5c141f2f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NzEwMzMsIm5iZiI6MTcxNjg3MDczMywicGF0aCI6Ii85NzYyMDc1NS8zMzQyMTUxMDMtOGQyNWE3ZDItYzEzMS00YWVlLTg1YmEtNGFjNWMxNDFmMmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA0MzIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYWQwNTliOTA3YWJkYzZlMDQ2NDc2MjQyNTgwZjUyY2VkNTIxYTQ3NTEyYzA2YzNlNDBhNGNiNWJmMjAzMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bFBfUa8CQ4cKic-xDI0HTRn5eJkmE7JphLEuxS_Jp6Q) change the upload class to that in the config.toml file
> > 
> > 
> > I already tried that but thanks for the suggestion
> 
> Hi did you solve your issue?

Not yet but what I found is people who have it work flawlessly are using Mac and even some of them have 0 views when I tried using a VPN to the Netherlands it blocked me but with the USA it was like normal but it didn't work again so it's a weird problem tbh

**Comment by cslop3r** [comment]
> > > > If you go over to the tiktok upload page and select the upload button with inspect element (in the part pointed by the arrow) ![image](https://private-user-images.githubusercontent.com/97620755/334215024-ef73f461-abfd-4d6f-8020-fc38c0031a31.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NzEwMzMsIm5iZiI6MTcxNjg3MDczMywicGF0aCI6Ii85NzYyMDc1NS8zMzQyMTUwMjQtZWY3M2Y0NjEtYWJmZC00ZDZmLTgwMjAtZmMzOGMwMDMxYTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA0MzIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwM2QzZGI1NWEyODNmZTZiZjgxZGIyYTI1ZTBjOTZlZDlmZTUzZThiZjdmYTAwYWE3MGFmMGZmZDBhM2I1NTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GTe9PFDiVb4sd6UZCYpVqf-W1rA2O49mdZF9RTFzQfw) You should see the button class. ![image](https://private-user-images.githubusercontent.com/97620755/334215103-8d25a7d2-c131-4aee-85ba-4ac5c141f2f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY4NzEwMzMsIm5iZiI6MTcxNjg3MDczMywicGF0aCI6Ii85NzYyMDc1NS8zMzQyMTUxMDMtOGQyNWE3ZDItYzEzMS00YWVlLTg1YmEtNGFjNWMxNDFmMmY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI4VDA0MzIxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQwYWQwNTliOTA3YWJkYzZlMDQ2NDc2MjQyNTgwZjUyY2VkNTIxYTQ3NTEyYzA2YzNlNDBhNGNiNWJmMjAzMjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bFBfUa8CQ4cKic-xDI0HTRn5eJkmE7JphLEuxS_Jp6Q) change the upload class to that in the config.toml file
> > > 
> > > 
> > > I already tried that but thanks for the suggestion
> > 
> > 
> > Hi did you solve your issue?
> 
> Not yet but what I found is people who have it work flawlessly are using Mac and even some of them have 0 views when I tried using a VPN to the Netherlands it blocked me but with the USA it was like normal but it didn't work again so it's a weird problem tbh

Hmm that's kinda weird. Also, I use a Mac and I have the problem

**Comment by mrTommorow** [comment]
ive managed to solve this problem by using the pyautogui libary to move the mouse to the relevent positions, if you just delete everything in the def _post_video(driver) and replace it with
    pyautogui.moveTo(1100, 300, duration=1)
    time.sleep(2)
    pyautogui.scroll(-500)
    time.sleep(2)
    pyautogui.moveTo(591, 776, duration=1)
    time.sleep(2)
    pyautogui.click(duration=1)
    time.sleep(4)
    pyautogui.moveTo(1170, 622, duration=1)
    time.sleep(3)
    pyautogui.click(duration=1)
    time.sleep(5)
    print("upload sucesfull")

you may have to adjust the x and y values to accommodate your screen resolution but with a little bit of tweaking it should work!

**Comment by Lucid-0x** [comment]
> ive managed to solve this problem by using the pyautogui libary to move the mouse to the relevent positions, if you just delete everything in the def _post_video(driver) and replace it with pyautogui.moveTo(1100, 300, duration=1) time.sleep(2) pyautogui.scroll(-500) time.sleep(2) pyautogui.moveTo(591, 776, duration=1) time.sleep(2) pyautogui.click(duration=1) time.sleep(4) pyautogui.moveTo(1170, 622, duration=1) time.sleep(3) pyautogui.click(duration=1) time.sleep(5) print("upload sucesfull")
> 
> you may have to adjust the x and y values to accommodate your screen resolution but with a little bit of tweaking it should work!

IT WORKS THANK YOU SO MUCH, YOU ARE A GOAT and this library got me too many ideas to do with and thanks again also good thing, Chrome didn't show the "the browser being run by an automated tool" so I guess this is a good thing and I will read the docs to see if I can make it headless but it totally fine for me without headless... i will leave the issue open in case any one wants to ask questions or the code is improved so we can pull it at the end

**Comment by LittleBitFishy** [comment]
> ive managed to solve this problem by using the pyautogui libary to move the mouse to the relevent positions, if you just delete everything in the def _post_video(driver) and replace it with pyautogui.moveTo(1100, 300, duration=1) time.sleep(2) pyautogui.scroll(-500) time.sleep(2) pyautogui.moveTo(591, 776, duration=1) time.sleep(2) pyautogui.click(duration=1) time.sleep(4) pyautogui.moveTo(1170, 622, duration=1) time.sleep(3) pyautogui.click(duration=1) time.sleep(5) print("upload sucesfull")
> 
> you may have to adjust the x and y values to accommodate your screen resolution but with a little bit of tweaking it should work!

ok im kinda stupid and i dont rlly understand much but im confused what even is this def _post_video(driver) thing like im so confused plz help bru

**Comment by LittleBitFishy** [comment]
> ive managed to solve this problem by using the pyautogui libary to move the mouse to the relevent positions, if you just delete everything in the def _post_video(driver) and replace it with pyautogui.moveTo(1100, 300, duration=1) time.sleep(2) pyautogui.scroll(-500) time.sleep(2) pyautogui.moveTo(591, 776, duration=1) time.sleep(2) pyautogui.click(duration=1) time.sleep(4) pyautogui.moveTo(1170, 622, duration=1) time.sleep(3) pyautogui.click(duration=1) time.sleep(5) print("upload sucesfull")
> 
> you may have to adjust the x and y values to accommodate your screen resolution but with a little bit of tweaking it should work!

hi ive been trying to get my one to work and this is the problem im getting and im not very good at this stuff and i dont rlly understand what you mean to replace the def _post_video(driver) with the code, i dont understand what and where that is, to me it seems like it is part of code that would be provided in this thread but i dont see any and i am confused
please help🙏

**Comment by Lucid-0x** [comment]
I can send a video or photo but what level you are in like have you installed python before can you locate the files of the library thro pip list do you have vs code etc

**Comment by jbosolutions** [comment]
C:\Users\jbbag\OneDrive\Escritorio\otro tik>tiktok-uploader -v video.mp4 -d "this is my escaped \"description\"" -c cookies.txt
[02:39:27] Authenticating browser with cookies
[02:39:27] Create a firefox browser instance in headless mode
[02:39:38] Authenticating browser with cookies
[02:39:41] Posting video.mp4
               with description: this is my escaped "description"
[02:39:41] Navigating to upload page
[02:39:45] Uploading video file
[02:39:48] Video should be uploading
[02:39:48] Video should be uploaded
Message:
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

[02:40:48] Failed to upload C:\Users\jbbag\OneDrive\Escritorio\otro tik\video.mp4
[02:40:48]
    A video failed to upload

-------------------------
Error while uploading video
-------------------------
