### ISSUE TITLE
Video uploaded successfully but does not appear in profile

### ISSUE THREAD

**Issue by tonysmiles** [wkaisertexas/tiktok-uploader#151]
I am having a problem: after the video is posted and the notification is successful, it does not appear in the profile. I am configuring posting with Firefox browser.

One interesting thing is that when I manually post the videos appear in my profile, does anyone have the same problem?  This problem seems very annoying

![1](https://github.com/wkaisertexas/tiktok-uploader/assets/44889451/f094fcab-56d6-47d7-b345-0058d45db753)

**Comment by wkaisertexas** [comment]
That does seem very annoying. I think this seems like a common issue. I would assume that only when the upload button is pressed does TikTok run a check to look at whether or not the uploaded video was uploaded by a human.

**Comment by tonysmiles** [comment]
> That does seem very annoying. I think this seems like a common issue. I would assume that only when the upload button is pressed does TikTok run a check to look at whether or not the uploaded video was uploaded by a human.

I switched to using Chrome's profile and combined posting videos to old accounts with previous views, the problem was resolved, only newly created accounts will have this problem.

**Comment by AlexisRSM** [comment]
@tonysmiles how did you do to add a Chrome profile when running? I think I might be having the same issue! I am posting manually everyday so the second part shouldn't be an issue right?
