### ISSUE TITLE
How to start it?

### ISSUE THREAD

**Issue by L1mexCodder** [wkaisertexas/tiktok-uploader#152]
Hello everyone! New to this topic, could you help me with running my script?

I created cookies and videos in separate folders, made a python script in which I prescribed the paths to cookies and videos, prescribed a proxy, how to run this script now so that it fills the video according to the parameters I set?

**Comment by wkaisertexas** [comment]
I would take a look at the examples folder.

**Comment by L1mexCodder** [comment]
> I would take a look at the examples folder.

Can you give me a folder with an example, please?
