### ISSUE TITLE
EOL while scanning string literal

### ISSUE THREAD

**Issue by L1mexCodder** [wkaisertexas/tiktok-uploader#154]
how to fix ? 
![image](https://github.com/wkaisertexas/tiktok-uploader/assets/132100025/6a61ea6a-75af-487b-bab5-5f42fa4ec566)

**Comment by wkaisertexas** [comment]
You have a python syntax error, you need to write it as follows

```python
"description": "#creditcard #bitbullrun #bullrun #ballonart #homeowner $xprcommunity"
```
