### ISSUE TITLE
Unable to schedule the video

### ISSUE THREAD

**Issue by artiemedvedev** [wkaisertexas/tiktok-uploader#156]
Unable to schedule the video

[15:01:21] Failed to set schedule: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='tux-3']"}
  (Session info: chrome=125.0.6422.114); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x009DB8E3+45827]
        (No symbol) [0x0096DCC4]
        (No symbol) [0x0086150F]
        (No symbol) [0x008A20BC]
        (No symbol) [0x008A216B]
        (No symbol) [0x008DE0F2]
        (No symbol) [0x008C2E44]
        (No symbol) [0x008DC034]
        (No symbol) [0x008C2B96]
        (No symbol) [0x00896998]
        (No symbol) [0x0089751D]
        GetHandleVerifier [0x00C94513+2899763]
        GetHandleVerifier [0x00CE793D+3240797]
        GetHandleVerifier [0x00A613B4+593364]
        GetHandleVerifier [0x00A682DC+621820]
        (No symbol) [0x009770A4]
        (No symbol) [0x009737A8]
        (No symbol) [0x00973947]
        (No symbol) [0x009659FE]
        BaseThreadInitThunk [0x757A7BA9+25]
        RtlInitializeExceptionChain [0x76FFBE7B+107]
        RtlClearBits [0x76FFBDFF+191]

**Comment by artiemedvedev** [comment]
after changing id to ":r12:" it manages to toggle schedule radio button but ends up with

[15:08:42] Uploading video file
[26484:49612:0604/150849.692:ERROR:device_event_log_impl.cc(195)] [15:08:49.678] USB: usb_service_win.cc:105 SetupDiGetDeviceProperty({{A45C254E-DF1C-4EFD-8020-67D146A850E0}, 6}) failed: Element not found. (0x490)
Created TensorFlow Lite XNNPACK delegate for CPU.
[15:08:56] Removing split window
[15:09:01] Split window not found or operation timed out
[15:09:01] Setting interactivity settings
[15:09:06] Failed to set interactivity settings
[15:09:06] Setting description
[15:09:08] Setting schedule
[15:09:08] Picking date
[15:09:14] Failed to set schedule: Message: 
Stacktrace:
        GetHandleVerifier [0x009DB8E3+45827]
        (No symbol) [0x0096DCC4]
        (No symbol) [0x0086150F]
        (No symbol) [0x008A20BC]
        (No symbol) [0x008A216B]
        (No symbol) [0x008DE0F2]
        (No symbol) [0x008C2E44]
        (No symbol) [0x008DC034]
        (No symbol) [0x008C2B96]
        (No symbol) [0x00896998]
        (No symbol) [0x0089751D]
        GetHandleVerifier [0x00C94513+2899763]
        GetHandleVerifier [0x00CE793D+3240797]
        GetHandleVerifier [0x00A613B4+593364]
        GetHandleVerifier [0x00A682DC+621820]
        (No symbol) [0x009770A4]
        (No symbol) [0x009737A8]
        (No symbol) [0x00973947]
        (No symbol) [0x009659FE]
        BaseThreadInitThunk [0x757A7BA9+25]
        RtlInitializeExceptionChain [0x76FFBE7B+107]
        RtlClearBits [0x76FFBDFF+191]

[15:09:14] Failed to upload D:\VIDEO STUDIO\Video Projects\2024-05-11_Horoscope_Daily\horoscopes\2024-06-10\2024-06-10_vertical.mov
[15:09:14]
    A video failed to upload

**Comment by joaovit1** [comment]
Same problem here, scheduling is not working

**Comment by yaniskata** [comment]
any news about this problem ?

**Comment by ib7x** [comment]
i have the same issue and i try to do some edit and add some features but i am Beginner in coding

**Comment by MarcoLavoro** [comment]
any news on how to solve this?

**Comment by mvenus2** [comment]
Why did this get closed?
