### ISSUE TITLE
NOT WORK

### ISSUE THREAD

**Issue by MarcoLavoro** [wkaisertexas/tiktok-uploader#159]
If I try the bot I get this

`C:\OFFLINEPROJECTS\BOTS\TikTokUploader3\tiktok-uploader>python main.py
[14:26:36] ←[92mAuthenticating browser with cookies←[0m
[14:26:36] Create a chrome browser instance

DevTools listening on ws://127.0.0.1:54709/devtools/browser/9ad784ab-ac0b-4c0a-b14a-5d935226e733
[14:26:39] Authenticating browser with cookies
[18508:11892:0613/142641.430:ERROR:ssl_client_socket_impl.cc(879)] handshake failed; returned -1, SSL error code 1, net_error -100
[18508:11892:0613/142641.441:ERROR:ssl_client_socket_impl.cc(879)] handshake failed; returned -1, SSL error code 1, net_error -100
[18508:11892:0613/142641.446:ERROR:ssl_client_socket_impl.cc(879)] handshake failed; returned -1, SSL error code 1, net_error -100
[18508:11892:0613/142641.559:ERROR:ssl_client_socket_impl.cc(879)] handshake failed; returned -1, SSL error code 1, net_error -107
[18508:11892:0613/142644.331:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
[14:26:44] Posting video.mp4
               with description: this is my description
[14:26:44] Navigating to upload page
[18508:11892:0613/142644.653:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
[18508:11892:0613/142646.391:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
[18508:11892:0613/142648.184:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
[18508:11892:0613/142648.356:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
[18508:11892:0613/142648.357:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
[18508:11892:0613/142651.351:ERROR:ssl_client_socket_impl.cc(879)] handshake failed; returned -1, SSL error code 1, net_error -100
[18508:11892:0613/142652.673:ERROR:ssl_client_socket_impl.cc(879)] handshake failed; returned -1, SSL error code 1, net_error -100
Created TensorFlow Lite XNNPACK delegate for CPU.
[18508:11892:0613/142702.904:ERROR:ssl_client_socket_impl.cc(879)] handshake failed; returned -1, SSL error code 1, net_error -100
[18508:11892:0613/142702.904:ERROR:ssl_client_socket_impl.cc(879)] handshake failed; returned -1, SSL error code 1, net_error -100
[14:27:47] Failed to upload C:\OFFLINEPROJECTS\BOTS\TikTokUploader3\tiktok-uploader\video.mp4
[14:27:47] Message:
Stacktrace:
        GetHandleVerifier [0x00F0B8E3+45827]
        (No symbol) [0x00E9DCC4]
        (No symbol) [0x00D9150F]
        (No symbol) [0x00DD20BC]
        (No symbol) [0x00DD216B]
        (No symbol) [0x00E0E0F2]
        (No symbol) [0x00DF2E44]
        (No symbol) [0x00E0C034]
        (No symbol) [0x00DF2B96]
        (No symbol) [0x00DC6998]
        (No symbol) [0x00DC751D]
        GetHandleVerifier [0x011C4513+2899763]
        GetHandleVerifier [0x0121793D+3240797]
        GetHandleVerifier [0x00F913B4+593364]
        GetHandleVerifier [0x00F982DC+621820]
        (No symbol) [0x00EA70A4]
        (No symbol) [0x00EA37A8]
        (No symbol) [0x00EA3947]
        (No symbol) [0x00E959FE]
        BaseThreadInitThunk [0x75FFFCC9+25]
        RtlGetAppContainerNamedObjectPath [0x770E7CBE+286]
        RtlGetAppContainerNamedObjectPath [0x770E7C8E+238]`
        
        there is a way to solve this or this just do not work anymore????

**Comment by Julien-paulet** [comment]
Hey, ran into the same issue with a fork I made on this repo ; For me, removing the switch to Iframe (right before uploading the video) worked

**Comment by cateyelow** [comment]
@Julien-paulet that makes sense. tiktok removed iframe

**Comment by MarcoLavoro** [comment]
> ving the switch to Ifram

thank you for the feedback, can you share with us in what point of the code we have to change to fix it?

**Comment by MarcoLavoro** [comment]
> Hey, ran into the same issue with a fork I made on this repo ; For me, removing the switch to Iframe (right before uploading the video) worked

thank you for the feedback, can you share with us in what point of the code we have to change to fix it?

**Comment by cateyelow** [comment]
@MarcoLavoro I fixed the issue and posted pull request. see this #160

**Comment by cateyelow** [comment]
@MarcoLavoro you're welcome. be happy day

**Comment by MarcoLavoro** [comment]
> Ok thank you!!
> 
> I see other people have problem with the schedule, did you solved that too?

Thank you! I tried your pull request and it work fine!
But if I try to schedule the video now I get:

[11:45:35] Failed to set schedule: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='tux-1']"}

Is that normal?

**Comment by cateyelow** [comment]
@MarcoLavoro I don't know detailed because i had never used the function. but as the logs you write, maybe the issue can solve by editing config.toml because of xpath.

**Comment by cateyelow** [comment]
@MarcoLavoro 
if you can analyze the xpath using dev console in the chrome, you can solve easily

**Comment by MarcoLavoro** [comment]
> @MarcoLavoro I don't know detailed because i had never used the function. but as the logs you write, maybe the issue can be solved by editing config.toml because of xpath.

Yes at the beginning  I) thought that and I changed in the config
	switch = "//*[@id='tux-1']"
to
	switch = "//*[@id=':r19:']"
	
	but thenk I get the error:
	[11:54:04] Failed to set schedule: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id=':r19:']"}
	
	so maybe I am missin something   :(

**Comment by cateyelow** [comment]
wait for a moment. I'll check it

**Comment by cateyelow** [comment]
@MarcoLavoro the main issue related all xpaths of schdule button, date picker, time picker.
So, it should takes few hours to fully fix

**Comment by iCodePup** [comment]
Hello, are you facing issue using tags in description ? The text of the tag appear but not the link.

**Comment by MarcoLavoro** [comment]
> @MarcoLavoro the main issue related all xpaths of schdule button, date picker, time picker. So, it should takes few hours to fully fix
> 
> Additional, switch = "//[@id=':r19:']" this not working becuase the id name be dynamic

thank you for the info!!!
Did you find a way to solve that and the schedule?

btw thanks for all your replies!!

**Comment by cateyelow** [comment]
@MarcoLavoro
You're welcome.
Actually I fixed 90% except time picker. however I had other schedule so i already went to other country. so, i have no time.
Can you solve remains if i give you uncompleted codes?

**Comment by joaovit1** [comment]
I am interested in fixing the schedule function as well, willing to help too if you give the uncompleted code, @cateyelow!

**Comment by cateyelow** [comment]
@joaovit1 
Here it is bro~
I fixed until time_pirkcer_containers, so start from timepicker_hours.
```
[selectors.schedule]
switch = "//input[@name='postSchedule' and @value='schedule']"

date_picker = "(//div[contains(@class, 'TUXTextInput')]/div/div/input[@type='text'])[2]"
calendar = "//div[contains(@class, 'calendar-wrapper')]"
calendar_month = "//span[contains(@class, 'month-title')]"
calendar_valid_days = "//div[@class='jsx-4172176419 days-wrapper']//span[contains(@class, 'day') and contains(@class, 'valid')]"
calendar_arrows = "//span[contains(@class, 'arrow')]"                                                                            # first last, second next

time_picker = "(//div[contains(@class, 'TUXTextInput')]/div/div/input[@type='text'])[1]"
time_picker_text = "(//div[contains(@class, 'TUXTextInput')]/div/div/input[@type='text'])[1]"
time_picker_container = "//div[@class='tiktok-timepicker-time-picker-container']"
timepicker_hours = "//span[contains(@class, 'tiktok-timepicker-left')]"
timepicker_minutes = "//span[contains(@class, 'tiktok-timepicker-right')]"

```

**Comment by MarcoLavoro** [comment]
> @joaovit1 Here it is bro~ I fixed until time_picker_containers, so start from timepicker_hours.
> 
> ```
> [selectors.schedule]
> switch = "//input[@name='postSchedule' and @value='schedule']"
> 
> date_picker = "(//div[contains(@class, 'TUXTextInput')]/div/div/input[@type='text'])[2]"
> calendar = "//div[contains(@class, 'calendar-wrapper')]"
> calendar_month = "//span[contains(@class, 'month-title')]"
> calendar_valid_days = "//div[@class='jsx-4172176419 days-wrapper']//span[contains(@class, 'day') and contains(@class, 'valid')]"
> calendar_arrows = "//span[contains(@class, 'arrow')]"                                                                            # first last, second next
> 
> time_picker = "(//div[contains(@class, 'TUXTextInput')]/div/div/input[@type='text'])[1]"
> time_picker_text = "(//div[contains(@class, 'TUXTextInput')]/div/div/input[@type='text'])[1]"
> time_picker_container = "//div[@class='tiktok-timepicker-time-picker-container']"
> timepicker_hours = "//span[contains(@class, 'tiktok-timepicker-left')]"
> timepicker_minutes = "//span[contains(@class, 'tiktok-timepicker-right')]"
> ```

thank you!
I am noob but I will see what I can do!

**Comment by cateyelow** [comment]
@MarcoLavoro 
I edited because reminded there's an issue on verifiy_time and verify_date

**Comment by quyetbg** [comment]
change xpath     switch = driver.find_element(
            By.XPATH, "//input[@value='schedule']"
        )  will work

**Comment by jbosolutions** [comment]
hello! im getting some errors:

C:\Users\jbbag\OneDrive\Escritorio\otro tik>tiktok-uploader -v video.mp4 -d "this is my escaped \"description\"" -c cookies.txt
[02:23:33] Authenticating browser with cookies
[02:23:33] Create a firefox browser instance in headless mode
[02:23:44] Authenticating browser with cookies
[02:23:47] Posting video.mp4
               with description: this is my escaped "description"
[02:23:47] Navigating to upload page
[02:23:50] Uploading video file
[02:23:53] Video should be uploading
[02:23:53] Video should be uploaded
Message:
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

[02:24:54] Failed to upload C:\Users\jbbag\OneDrive\Escritorio\otro tik\video.mp4
[02:24:54]
    A video failed to upload

-------------------------
Error while uploading video
-------------------------




may you help me?

**Comment by jbosolutions** [comment]
> Hey, ran into the same issue with a fork I made on this repo ; For me, removing the switch to Iframe (right before uploading the video) worked

hey how?

**Comment by Julien-paulet** [comment]
> > Hey, ran into the same issue with a fork I made on this repo ; For me, removing the switch to Iframe (right before uploading the video) worked
> 
> hey how?

I did not read the full conversation here but from what I saw the problem is fixed, maybe try updating the lib to its last version ? 
Otherwise, from memory there is a function "switch_to_iframe" in the function "_go_to_upload" that you need to comment

My fork differs quite a lot from the main repo, so I will not be able to help you more than this :/
