### ISSUE TITLE
I am unable to upload the video

### ISSUE THREAD

**Issue by P3eky** [wkaisertexas/tiktok-uploader#163]
It successfully opens chrome, logs in with the cookies, and navigates to the upload screen, however I get the following error once I am on the upload screen.

[8680:5628:0619/181515.053:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
[8680:5628:0619/181516.544:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
[8680:5628:0619/181517.303:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105
[8680:5628:0619/181517.874:ERROR:socket_manager.cc(141)] Failed to resolve address for stun.l.google.com., errorcode: -105

[18:20:57] Failed to upload D:\Storage\!MotivationalMorning\video.mp4
[18:20:57] Message:
Stacktrace:
        GetHandleVerifier [0x0096B8E3+45827]
        (No symbol) [0x008FDCC4]
        (No symbol) [0x007F150F]
        (No symbol) [0x008320BC]
        (No symbol) [0x0083216B]
        (No symbol) [0x0086E0F2]
        (No symbol) [0x00852E44]
        (No symbol) [0x0086C034]
        (No symbol) [0x00852B96]
        (No symbol) [0x00826998]
        (No symbol) [0x0082751D]
        GetHandleVerifier [0x00C24513+2899763]
        GetHandleVerifier [0x00C7793D+3240797]
        GetHandleVerifier [0x009F13B4+593364]
        GetHandleVerifier [0x009F82DC+621820]
        (No symbol) [0x009070A4]
        (No symbol) [0x009037A8]
        (No symbol) [0x00903947]
        (No symbol) [0x008F59FE]
        BaseThreadInitThunk [0x75E2FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77AB80CE+286]
        RtlGetAppContainerNamedObjectPath [0x77AB809E+238]
        
        I am currently using the most recent version of tiktok-uploader obtained using
pip install git+https://github.com/wkaisertexas/tiktok-uploader
 and Google Chrome 125.0.6422.144 (Official Build) (64-bit) .

**Comment by P3eky** [comment]
[18:20:57] Failed to upload D:\Storage\!MotivationalMorning\video.mp4
[18:20:57] Message:
Stacktrace:
        GetHandleVerifier [0x0096B8E3+45827]
        (No symbol) [0x008FDCC4]
        (No symbol) [0x007F150F]
        (No symbol) [0x008320BC]
        (No symbol) [0x0083216B]
        (No symbol) [0x0086E0F2]
        (No symbol) [0x00852E44]
        (No symbol) [0x0086C034]
        (No symbol) [0x00852B96]
        (No symbol) [0x00826998]
        (No symbol) [0x0082751D]
        GetHandleVerifier [0x00C24513+2899763]
        GetHandleVerifier [0x00C7793D+3240797]
        GetHandleVerifier [0x009F13B4+593364]
        GetHandleVerifier [0x009F82DC+621820]
        (No symbol) [0x009070A4]
        (No symbol) [0x009037A8]
        (No symbol) [0x00903947]
        (No symbol) [0x008F59FE]
        BaseThreadInitThunk [0x75E2FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77AB80CE+286]
        RtlGetAppContainerNamedObjectPath [0x77AB809E+238]

**Comment by felipexpert** [comment]
I am not able to upload videos too. Did somebody find a solution?
