### ISSUE TITLE
New tiktok issue ALERT

### ISSUE THREAD

**Issue by jbosolutions** [wkaisertexas/tiktok-uploader#166]
[02:56:23] Create a firefox browser instance in headless mode
[02:56:35] Authenticating browser with cookies
[02:56:38] Posting video.mp4
               with description: this is my escaped "description"
[02:56:38] Navigating to upload page
[02:56:40] Uploading video file
[02:56:44] Video should be uploading
[02:56:44] Video should be uploaded
Message:
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:511:5
dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:136:16

[02:57:45] Failed to upload C:\Users\jbbag\OneDrive\Escritorio\otro tik\video.mp4
[02:57:45]
    A video failed to upload

-------------------------
Error while uploading video
-------------------------

SOMEONE knows how to fix it?!

**Comment by Impre-visible** [comment]
I'm on ubuntu 22.04, same issue

**Comment by JamesD-git** [comment]
Hi folks, Tiktok changed from an input iframe to just an input - by changing the _change_to_upload_iframe(driver) code to """
<code goes here>
"""
pass

Not an ideal workaround, but might help

**Comment by Fondyxs** [comment]
> Привет, ребята, TikTok изменился с входного iframe на просто входной - изменив код _change_to_upload_iframe(driver) на """ ` """ pass`
> 
> ` Not an ideal workaround, but might help`

thank you!
