### ISSUE TITLE
eror

### ISSUE THREAD

**Issue by qweaeqew** [wkaisertexas/tiktok-uploader#17]
i trying to use this but getting error 

> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\Danil\AppData\Local\Programs\Python\Python311\Scripts\tiktok-uploader.exe\__main__.py", line 7, in <module>
>   File "C:\Users\Danil\tiktok-uploader\src\tiktok_uploader\cli.py", line 20, in main
>     result = upload_video(
>              ^^^^^^^^^^^^^
>   File "C:\Users\Danil\tiktok-uploader\src\tiktok_uploader\upload.py", line 41, in upload_video
>     auth = AuthBackend(username=username, password=password, cookies=cookies)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Danil\tiktok-uploader\src\tiktok_uploader\auth.py", line 39, in __init__
>     raise InsufficientAuth()
> tiktok_uploader.auth.InsufficientAuth:
>     Insufficient authentication:
> 
>     > TikTok uses cookies to keep track of the user's authentication or session.
> 
>     Either:
>         - Use a cookies file passed as the `cookies` argument
>             - easily obtained using https://github.com/kairi003/Get-cookies.txt-LOCALLY
>         - Use a cookies list passed as the `cookies_list` argument
>             - can be obtained from your browser's developer tools under storage -> cookies
>             - only the `sessionid` cookie is required
> 

but i fill txt file 
(like this:
xxxxxxxxxxxxx
xxxxxxxxxxxxx)

**Comment by wkaisertexas** [comment]
The text file should be filled with your cookies. I would recommend the top option which it gives you 

> - Use a cookies file passed as the `cookies` argument
        - easily obtained using https://github.com/kairi003/Get-cookies.txt-LOCALLY

**Comment by wkaisertexas** [comment]
If you are still getting this error, this means that you are not passing the file path to 'upload_videos'.

The program needs to know where to get the cookies.
