### ISSUE TITLE
Timeout Exception on Video Upload

### ISSUE THREAD

**Issue by zahiTouqan** [wkaisertexas/tiktok-uploader#170]
I am getting this error while trying to upload videos:
TimeoutException occurred:
 Message: 
Stacktrace:
#0 0x605c49bf5c5a <unknown>
#1 0x605c498d8e2c <unknown>
#2 0x605c49925661 <unknown>
#3 0x605c49925751 <unknown>
#4 0x605c49969f64 <unknown>
#5 0x605c499485ed <unknown>
#6 0x605c49967303 <unknown>
#7 0x605c49948363 <unknown>
#8 0x605c49918247 <unknown>
#9 0x605c49918b9e <unknown>
#10 0x605c49bbc22b <unknown>
#11 0x605c49bc02d1 <unknown>
#12 0x605c49ba7ade <unknown>
#13 0x605c49bc0e32 <unknown>
#14 0x605c49b8c77f <unknown>
#15 0x605c49be5618 <unknown>
#16 0x605c49be57f0 <unknown>
#17 0x605c49bf4d8c <unknown>
#18 0x7de5b7c9ca94 <unknown>
#19 0x7de5b7d29c3c <unknown>

then it fails afterwards. Does anyone know why or how to fix it?

EDIT: after testing it appears that is due to the captcha popping up, did anybody find a workaround for that yet?

**Comment by guillaume-gex** [comment]
Hello the same for me ...

I get to this:

[23:53:58] Navigating to upload page

and hang on the select video page on TikTok...  nothing happens...

Can anyone help me please ? Thank you
