### ISSUE TITLE
Error while uploading a video

### ISSUE THREAD

**Issue by Yannis-Zribi** [wkaisertexas/tiktok-uploader#171]
Here is the command I'm using : 
tiktok-uploader -v video.mp4 -d "this is my escaped \"description\"" -c cookie.txt

Here is the error I'm facing : 

[17:34:39] Authenticating browser with cookies
[17:34:39] Create a chrome browser instance in headless mode
[17:34:39] Authenticating browser with cookies
[17:34:42] Posting video.mp4
               with description: this is my escaped "description"
[17:34:42] Navigating to upload page
[17:35:45] Failed to upload /home/debian/video.mp4
[17:35:45] Message:
Stacktrace:
#0 0x570a83e746aa <unknown>
#1 0x570a83b45600 <unknown>
#2 0x570a83b94bcb <unknown>
#3 0x570a83b94eb1 <unknown>
#4 0x570a83bd8b24 <unknown>
#5 0x570a83bb78cd <unknown>
#6 0x570a83bd604a <unknown>
#7 0x570a83bb7643 <unknown>
#8 0x570a83b87d31 <unknown>
#9 0x570a83b8879e <unknown>
#10 0x570a83e3c23b <unknown>
#11 0x570a83e401d2 <unknown>
#12 0x570a83e295f5 <unknown>
#13 0x570a83e40d62 <unknown>
#14 0x570a83e0e23f <unknown>
#15 0x570a83e63e48 <unknown>
#16 0x570a83e64020 <unknown>
#17 0x570a83e7347c <unknown>
#18 0x7c414ed4b39d <unknown>
#19 0x7c414edd049c <unknown>

-------------------------
Error while uploading video
-------------------------

I don't really understand the stack trace. I tried to upload with the username and password but I get the same error.

I also tried with the code version by calling the function but the code freeze and then crash...

If someone has an idea on how I can fix this ?

**Comment by 3ovutVanja** [comment]
same problem(
Did you solve it?

**Comment by wdoer** [comment]
Guys who are reading this thread in the hopes Read recently closed this problem. 

Ticktock added captcha and the solution is to implement autoresolver. There are no free services for this on my memory, so try to create a new script based on Tik Tok Api. 

Most likely this option is out of the question, look for other ways.
