### ISSUE TITLE
Error during upload

### ISSUE THREAD

**Issue by letruxux** [wkaisertexas/tiktok-uploader#19]
console spammed with `Failed to resolve address for stun.l.google.com., errorcode: -105`
then `Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@type='file']"}`

**Comment by ricardopereirasilveira** [comment]
the same behavior here.

**Comment by ricardopereirasilveira** [comment]
@letruxux change the language to EN and get the cookies again. Works here. Its not an issue.

**Comment by joseluissaorin** [comment]
Got the same issue and that fixed it

**Comment by wlauton** [comment]
i tried setting language to english, but still getting the issue , this still working?

**Comment by letruxux** [comment]
> @letruxux change the language to EN and get the cookies again. Works here. Its not an issue.
yeah that worked
