### ISSUE TITLE
"video" word before description

### ISSUE THREAD

**Issue by Devstored** [wkaisertexas/tiktok-uploader#2]
<img width="220" alt="image" src="https://user-images.githubusercontent.com/46482210/221889373-b174572c-14ff-445e-a21d-765773320254.png">

There is the word "video" in front of my description which is added each time I upload a video.
However, it does not add it during my tests.
For example if my description is "tata" then the upload will be done correctly but when I go to Tiktok in the description of my video it will be indicated: "videotata"

**Comment by wkaisertexas** [comment]
I ended up finding out about this issue recently as well. The code clears the field with Selenium's `element.clear` method.

This ends up not working when the computer is asleep for some reason.  

Going to try and execute a javascript command and see if that ends up fixing things.

**Comment by wkaisertexas** [comment]
`video` being in front of your description comes directly from the filename which overwrites the description box as soon as it is uploaded. 

However, filling the box with a description first prevents this when I upload the video manually. 

I am not sure if this will work when automated, but it is definitely something I will look into over the next few days.

**Comment by Devstored** [comment]
> `video` being in front of your description comes directly from the filename which overwrites the description box as soon as it is uploaded.
> 
> However, filling the box with a description first prevents this when I upload the video manually.
> 
> I am not sure if this will work when automated, but it is definitely something I will look into over the next few days.

It's very clear, thank you for your answer. I will see if your solution works.

**Comment by Devstored** [comment]
I found a workaround @wkaisertexas . It is no longer necessary to do a desc.clear(). You can use the code:
int_desc = len(description)
desc.send_keys(int_desc * Keys.BACKSPACE)

Good luck for the rest of the development, it's really great what you're doing.

**Comment by wkaisertexas** [comment]
I am about to release a new version which will have proper support for @'s, #'s and privacy settings. I am a little dumb and have been making my commits on main so I am going to wait to push it.

[React Selenium Issues](https://github.com/SeleniumHQ/selenium/issues/6741) shows how the clear function does not work well with react inputs.

**Comment by wkaisertexas** [comment]
@Devstored 

v0.1.2 Fixes the issue of the filename persisting despite clearing. Additionally, it adds support for mentions and hashtags. 

Thanks so much for the suggestions.
