### ISSUE TITLE
Video scheduling

### ISSUE THREAD

**Issue by MrUnreal** [wkaisertexas/tiktok-uploader#21]
Heya - I started adding video scheduling to this - I was wondering, do you want other people to raise PRs against your code or do you prefer solo contribution ?

**Comment by ricardopereirasilveira** [comment]
very nice, if you fork it, lets me know to clone your fork. Thank you.

**Comment by wkaisertexas** [comment]
Other people being willing to work on your code is a great complement. I would be happy to answer any questions which you may have.

From an organization perspective, setting a scheduled time should be an extra step for `upload.py`'s `complete_upload_form` function which goes sequentially to upload the video.

- `_go_to_upload`
- ` _set_video` -> uploads the video (name a little confusing)
-  `_set_interactivity`
-  ` _set_description`
-  ` _post_video`

Adding a scheduling step after `_set_description` would be great. When selecting DOM elements, I only ask that the sector paths be put into `config.toml`.

**Comment by XavierZambrano** [comment]
I'm working on it, in a pair of days I will make a PR 

https://github.com/XavierZambrano/tiktok-uploader

**Comment by ashevs** [comment]
hi @XavierZambrano xavier ,
how to add command schedule in below commnd

from tiktok_uploader.upload import upload_videos
from tiktok_uploader.auth import AuthBackend

videos = [
    {
        'video': 'video0.mp4',
        'description': 'Video 1 is about ...'
    },
    {
        'video': 'video1.mp4',
        'description': 'Video 2 is about ...'
    }
]

auth = AuthBackend(cookies='cookies.txt')
failed_videos = upload_videos(videos=videos, auth=auth)

for video in failed_videos: # each input video object which failed
    print(f'{video['video']} with description "{video['description']}" failed')

**Comment by XavierZambrano** [comment]
@ashevs check my fork https://github.com/XavierZambrano/tiktok-uploader


```
import datetime
schedule = datetime.datetime(2020, 12, 20, 13, 00)
upload_video(..., schedule=schedule)
```

**Comment by wkaisertexas** [comment]
Great PR @XavierZambrano. Sorry reviewing it took me too long
