### ISSUE TITLE
The new "split into multiple parts" feature on longer videos messes up the upload

### ISSUE THREAD

**Issue by rn3r** [wkaisertexas/tiktok-uploader#22]
There is a popup that tries to get you to try the new feature they added, splitting into multiple parts
the popup prevents the uploader from interacting with the page, therefore causing errors
It would also be nice to see the split feature added in the arguments for the video upload

**Comment by nullptrmachine** [comment]
+
It messes up the uploading of multiple videos. Somehow glitches and iterates over all videos and also calls successful upload callback so it's messed my already uploaded videos list.
This needs to be fixed somehow please

**Comment by wkaisertexas** [comment]
I honestly have never used this feature. It looks like TikTok is doing a lot of updates to their Desktop application recently, and I unfortunately have not been able to keep pace.

When uploading multiple videos, you need to inspect the returned object to get a list of videos which failed.
