### ISSUE TITLE
Doesn't work if the language is not English

### ISSUE THREAD

**Issue by Denintendator** [wkaisertexas/tiktok-uploader#23]
I spent a long time trying to figure out what the problem was, I had to look into the selectors to figure out what was wrong. Understanding the problem, I changed the language to English, updated the cookies and everything worked. I think we should at least make a note that English is required

**Comment by wkaisertexas** [comment]
I will update the documentation. One of the selectors that I use requires an English-language description, and I need to find a way to update this to still be durable without requiring on an English-langauge description.
