### ISSUE TITLE
How to add music from Tiktok to video when upload 

### ISSUE THREAD

**Issue by lavanphat** [wkaisertexas/tiktok-uploader#24]
Hi. This is a great tool to automatically upload videos to tiktok. Can you provide more functionality to add music on Tiktok to videos in future sessions?

**Comment by wkaisertexas** [comment]
Adding a "sound" to TikTok from their web portal is currently not available. 

Unless this feature is added, I can not really upload the video. 

Sorry about this.

**Comment by impec0762** [comment]
Feature is added now on TikTok web portal
Please update
