### ISSUE TITLE
basic_upload.py source video file missing

### ISSUE THREAD

**Issue by WilliamSadler** [wkaisertexas/tiktok-uploader#27]
The video file originally hosted at https://raw.githubusercontent.com/wkaisertexas/wkaisertexas.github.io/main/upload.mp4 is currently unavailable, as such the basic_upload.py example script is currently not working.

This may just be a temporary issue but it may have been removed by accident. 😊

**Comment by wkaisertexas** [comment]
Oh shit, I redid my personal website and could not wonder for the life of me what that file was for. Really sorry about that. I will probably find some other video file on the internet.
