### ISSUE TITLE
Add compatibility with Raspberry Pi and a potential issue

### ISSUE THREAD

**Issue by tidusete** [wkaisertexas/tiktok-uploader#3]
Hi there,
I have been using your product and I think it's great! However, I noticed that it's not compatible with Raspberry Pi 4 out of the box. In order to make it work with Raspberry Pi 4, I had to make a few modifications to the source code which I've included below:

```
diff .venv/tiktok-uploader/lib/python3.9/site-packages/tiktok_uploader/ src/tiktok_uploader/
diff .venv/tiktok-uploader/lib/python3.9/site-packages/tiktok_uploader/browsers.
py src/tiktok_uploader/browsers.py
177c177
<     'chrome': lambda : ChromeService('/usr/bin/chromedriver'),
---
>     'chrome': lambda : ChromeService(ChromeDriverManager().install()),
Only in .venv/tiktok-uploader/lib/python3.9/site-packages/tiktok_uploader/: __py                                                                                                                                                             cache__

```
I hope this will be useful for other Raspberry Pi users who would like to use your product. However, I also want to note that in my experience, there is a potential issue with the Raspberry Pi freezing while attempting to upload the video. This has happened to me a few times while using your product on my Raspberry Pi. I'm not sure if this is related to the modifications I made or if it's a separate issue, but I wanted to bring it to your attention nonetheless.

Please let me know if you have any questions or if there's anything else I can do to help. Thank you for your time and consideration.

I have to keep investigating and maybe go for a more lightweight solution

**Comment by wkaisertexas** [comment]
Hey, this was actually a point of consideration with the API design. I tried to make the browser settings flexible to not cause browser lock. Raspberry Pis were definitely not something that I was considering for making this project. For that reason, there is the option to pass a custom `browser_agent` to `upload_video` or `upload_videos`. 

When getting the browser's driver, I decided to base the library's default solution around `webdriver_manager` which is supported by Selenium. This really helps remove the pain of installing and keeping track of webdriver versions, greatly increasing portability.

However, to keep flexibility high, I gave the option to pass a custom `browser-agent` which bypasses `browsers.py` completely. You can also pass custom driver `options` if you wanted to tweak settings to make the library less detectable for example.

Thank you for your concern though, and I will try and think about how I can make that more clear in the documentation.
