### ISSUE TITLE
Issue with: driver by url

### ISSUE THREAD

**Issue by diegotrasobares** [wkaisertexas/tiktok-uploader#31]
Hey!! I have been having troubles to upload videos. The process get stuck when creating browser instance:
`  File "C:\Users\traso\Desktop\Tiktok\venv\Lib\site-packages\webdriver_manager\core\http.py", line 16, in validate_response
    raise ValueError(f"There is no such driver by url {resp.url}")
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/LATEST_RELEASE_115.0.5790`
If you click the link where it is supposed to be the driver, it's not working, so I guess that's the problem. I don't know how I'm supposed to fix this. Should we replace the url from the driver?
Thanks in advance!!! 
@wkaisertexas

**Comment by XavierZambrano** [comment]
This can be related https://github.com/ultrafunkamsterdam/undetected-chromedriver/issues/1402#issuecomment-1656729399

**Comment by wkaisertexas** [comment]
This is something that I will have to look more into and was my issue upon a fresh clone of the system...

Likely a webdriver manager issue, but I currently do not know a workaround.
