### ISSUE TITLE
Upload fails when setting interactivity settings and description

### ISSUE THREAD

**Issue by joseluissaorin** [wkaisertexas/tiktok-uploader#32]
Whenever I upload it goes as expected until it reaches the interactivity settings and it fails, then, when it reachesthe point of setting the description it fails again and gives the following error: element not interactable 

![image](https://github.com/wkaisertexas/tiktok-uploader/assets/15180226/ef46a5fa-d064-4f8c-8c17-084458cdb62d)

**Comment by rpereira90** [comment]
same issue, did you manage to find a solution ? @joseluissaorin

**Comment by wkaisertexas** [comment]
I think this is because of a popup which TikTok is trying to get you into a promotion.

The modal locks up the page making the element selected not interact-able.
