### ISSUE TITLE
cannot login to tiktok account

### ISSUE THREAD

**Issue by simoistgray** [wkaisertexas/tiktok-uploader#34]
I pass in the cookies and valid video file and the code will pull up a chrome window, but then get stuck on the login page, eventually leading to an error. I have tried multiple different tiktok accounts to test if that was the problem, but no luck. When the chrome page loads up tiktok, I think it gets stuck on the human verification task that tiktok prompts users with to make sure they are human. It only pops up for a blink, but I can't think of any other reason this would be happening.

**Comment by Mehliug-git** [comment]
I have solve my problem, just use a dictionary instead of cookie.txt

**Comment by wkaisertexas** [comment]
`cookie.txt` is not working like I hoped. Using it for a cookie-hack was too contrived to be effective.
