### ISSUE TITLE
Error while uploading video

### ISSUE THREAD

**Issue by ashevs** [wkaisertexas/tiktok-uploader#36]
on 26/8 friday is still ok can upload videos
but today 27/8 error when uploading

[14:34:29] ←[92mAuthenticating browser with cookies←[0m
[14:34:29] Create a chrome browser instance in headless mode

DevTools listening on ws://127.0.0.1:57538/devtools/browser/782c7b28-6f06-4dca-88de-f15934c5999e
[14:34:44] Authenticating browser with cookies
[14:35:04] Posting video0007.mp4
               with description: this is my escaped from the worl
[14:35:04] Navigating to upload page
[14:35:08] Uploading video file
Message:
Stacktrace:
        GetHandleVerifier [0x00E737C3+48947]
        (No symbol) [0x00E08551]
        (No symbol) [0x00D0C92D]
        (No symbol) [0x00D39E38]
        (No symbol) [0x00D39EFB]
        (No symbol) [0x00D68EF2]
        (No symbol) [0x00D550D4]
        (No symbol) [0x00D675DA]
        (No symbol) [0x00D54E86]
        (No symbol) [0x00D316C7]
        (No symbol) [0x00D3284D]
        GetHandleVerifier [0x010BFDF9+2458985]
        GetHandleVerifier [0x0110744F+2751423]
        GetHandleVerifier [0x01101361+2726609]
        GetHandleVerifier [0x00EF0680+560624]
        (No symbol) [0x00E1238C]
        (No symbol) [0x00E0E268]
        (No symbol) [0x00E0E392]
        (No symbol) [0x00E010B7]
        BaseThreadInitThunk [0x760000C9+25]
        RtlGetAppContainerNamedObjectPath [0x77587B1E+286]
        RtlGetAppContainerNamedObjectPath [0x77587AEE+238]

Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@type='file']"}
  (Session info: chrome=116.0.5845.111); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x00E737C3+48947]
        (No symbol) [0x00E08551]
        (No symbol) [0x00D0C92D]
        (No symbol) [0x00D39E38]
        (No symbol) [0x00D39EFB]
        (No symbol) [0x00D68EF2]
        (No symbol) [0x00D550D4]
        (No symbol) [0x00D675DA]
        (No symbol) [0x00D54E86]
        (No symbol) [0x00D316C7]
        (No symbol) [0x00D3284D]
        GetHandleVerifier [0x010BFDF9+2458985]
        GetHandleVerifier [0x0110744F+2751423]
        GetHandleVerifier [0x01101361+2726609]
        GetHandleVerifier [0x00EF0680+560624]
        (No symbol) [0x00E1238C]
        (No symbol) [0x00E0E268]
        (No symbol) [0x00E0E392]
        (No symbol) [0x00E010B7]
        BaseThreadInitThunk [0x760000C9+25]
        RtlGetAppContainerNamedObjectPath [0x77587B1E+286]
        RtlGetAppContainerNamedObjectPath [0x77587AEE+238]

Message: no such element: Unable to locate element: {"method":"xpath","selector":"//input[@type='file']"}
  (Session info: chrome=116.0.5845.111); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
        GetHandleVerifier [0x00E737C3+48947]
        (No symbol) [0x00E08551]
        (No symbol) [0x00D0C92D]
        (No symbol) [0x00D39E38]
        (No symbol) [0x00D39EFB]
        (No symbol) [0x00D68EF2]
        (No symbol) [0x00D550D4]
        (No symbol) [0x00D675DA]
        (No symbol) [0x00D54E86]
        (No symbol) [0x00D316C7]
        (No symbol) [0x00D3284D]
        GetHandleVerifier [0x010BFDF9+2458985]
        GetHandleVerifier [0x0110744F+2751423]
        GetHandleVerifier [0x01101361+2726609]
        GetHandleVerifier [0x00EF0680+560624]
        (No symbol) [0x00E1238C]
        (No symbol) [0x00E0E268]
        (No symbol) [0x00E0E392]
        (No symbol) [0x00E010B7]
        BaseThreadInitThunk [0x760000C9+25]
        RtlGetAppContainerNamedObjectPath [0x77587B1E+286]
        RtlGetAppContainerNamedObjectPath [0x77587AEE+238]

[14:35:45] Failed to upload E:\TikTok\tiktok-uploader4\video0007.mp4
[14:35:45]
    A video failed to upload

-------------------------
Error while uploading video

please check kaise how to solve...many many thanks

**Comment by piriyaraj** [comment]
recently they changed the interface so Try the below solution


in the config.toml file
change line  21

upload = "https://www.tiktok.com/upload?lang=en"
to
upload = "https://www.tiktok.com/creator-center/upload?lang=en"

**Comment by ashevs** [comment]
hi @piriyaraj thanks for the solution,
but only success with command single video

when do multi upload videos have error, and only first video uploaded, the rest is failed

[18:18:48] ←[92mAuthenticating browser with cookies←[0m
[18:18:48] Uploading 10 videos
[18:18:48] Create a chrome browser instance

DevTools listening on ws://127.0.0.1:52523/devtools/browser/612ac1a2-bce4-43b3-b4d7-376ffc0fdc53
[18:19:03] Authenticating browser with cookies
[18:19:15] Posting video001.mp4
               with description: Thanks-001
[18:19:15] Navigating to upload page
[18:19:22] Uploading video file
[18:20:01] Setting interactivity settings
[18:20:01] Setting description
[18:20:02] Clicking the post button
[18:20:17] Video posted successfully
[18:20:17] Posting video002.mp4
               with description: Thanks-002
[18:20:17] Navigating to upload page
[18:20:17] Failed to upload E:\TikTok\tiktok-uploader4\video002.mp4
[18:20:17] Alert Text: {Alert text :
Message: unexpected alert open: {Alert text : }
  (Session info: chrome=116.0.5845.111)
Stacktrace:
        GetHandleVerifier [0x002437C3+48947]
        (No symbol) [0x001D8551]
        (No symbol) [0x000DC92D]
        (No symbol) [0x00137AAD]
        (No symbol) [0x00124E86]
        (No symbol) [0x001016C7]
        (No symbol) [0x0010284D]
        GetHandleVerifier [0x0048FDF9+2458985]
        GetHandleVerifier [0x004D744F+2751423]
        GetHandleVerifier [0x004D1361+2726609]
        GetHandleVerifier [0x002C0680+560624]
        (No symbol) [0x001E238C]
        (No symbol) [0x001DE268]
        (No symbol) [0x001DE392]
        (No symbol) [0x001D10B7]
        BaseThreadInitThunk [0x760000C9+25]
        RtlGetAppContainerNamedObjectPath [0x77587B1E+286]
        RtlGetAppContainerNamedObjectPath [0x77587AEE+238]
        (No symbol) [0x00000000]

can you check?
thanks for your help

**Comment by wkaisertexas** [comment]
Creator center is in beta if I am not mistaken. 

Did it move in an out of beta? I really don't know, but I was not able to have access to this.
