### ISSUE TITLE
"Split video" pop up makes me unable to upload the video.

### ISSUE THREAD

**Issue by thetribecalledquest** [wkaisertexas/tiktok-uploader#45]
If I click the "not now" button, the file uploads sucessfully, but without any interaction the program fails. Could someone help me fix this? 

**Thank you in advance**

![obraz](https://github.com/wkaisertexas/tiktok-uploader/assets/145489823/a5792a35-9a4b-452b-a4ab-ab5dc135ce37)

**Comment by thetribecalledquest** [comment]
Yes, you are correct.

**Comment by wkaisertexas** [comment]
Similar to #57
