### ISSUE TITLE
There is no such driver by url

### ISSUE THREAD

**Issue by Snej-Corleone** [wkaisertexas/tiktok-uploader#49]
When I start the script, I get the following error: There is no such driver at the URL `https://chromedriver.storage.googleapis.com/117.0.5938/chromedriver_mac64.zip`. 
Can I simply change the required string to a newer version of Chrome? If so, where should I do this? 

Thank you for any help!

**Comment by XavierZambrano** [comment]
https://github.com/wkaisertexas/tiktok-uploader/issues/31

**Comment by wkaisertexas** [comment]
Yeah, this is a web driver manager issue if I am not mistaken.

I am still looking into solutions. Sorry about that.
