### ISSUE TITLE
Schedule not working

### ISSUE THREAD

**Issue by diegotrasobares** [wkaisertexas/tiktok-uploader#50]
When I try to upload one video using the datetime for schedule it always fails with the following message:

> Failed to set schedule: Something went wrong with the time picker, expected 18:00 but got 17:00
> [17:11:30] Something went wrong with the time picker, expected 18:00 but got 17:00
> [17:11:30] Failed to set schedule: Something went wrong with the time picker, expected 18:00 but got 17:00

My code is very simple:
```
 import datetime
from tiktok_uploader.upload import upload_video

schedule = datetime.datetime(2023, 9, 26, 18, 0)
upload_video(filename="../result/part_1_with_text.mp4",description="Just a test" ,cookies="./static/cookies.txt",
             schedule=schedule) 
```

Any thoughts?

**Comment by wkaisertexas** [comment]
@XavierZambrano wrote the scheduler code

**Comment by XavierZambrano** [comment]
`def __time_picker` is not working fine

You can try to :
1. add time.sleep() between 
`    driver.execute_script("arguments[0].scrollIntoView({block: 'center', inline: 'nearest'});", hour_to_click)
    hour_to_click.click()`
2. Check if the selector changed
`    hour_options = driver.find_elements(By.XPATH, config['selectors']['schedule']['timepicker_hours'])`
3. Execute without headless and watch what is happening
