### ISSUE TITLE
# hastags do not work.

### ISSUE THREAD

**Issue by JoonyWoony** [wkaisertexas/tiktok-uploader#52]

**Comment by JoonyWoony** [comment]
hashtags (#) works in firefox, but does not seem to work on chrome. a fix?

**Comment by israel177** [comment]
hello  @wkaisertexas @XavierZambrano  @gqmv 
I use chrome and the hastahg no longer works, even use headless chrome

**Comment by LevaniVashadze** [comment]
For me hashtags work but tagging people doesn't work

**Comment by LevaniVashadze** [comment]
[15:52:39] Message: element not interactable
  (Session info: chrome=117.0.5938.150)
this is the error when that happens

**Comment by wkaisertexas** [comment]
I will look at this for the next release. I know I made a mistake in the hashtag selecting code which meant that if a hashtag was not followed by a space, it could not be properly detected.

Thanks for the report.

**Comment by Felix-Jonathan** [comment]
Hello ! I Can upload but # list is just a string ... Bug was resolve ?

**Comment by wkaisertexas** [comment]
An early version of the uploader just uploaded the string, are you sure your module is up to date?
