### ISSUE TITLE
Scheduler fails, one hour difference

### ISSUE THREAD

**Issue by HasseM** [wkaisertexas/tiktok-uploader#59]
In about 50% of the cases the scheduler seems to be one hour off. I get for example: Failed to set schedule: Something went wrong with the time picker, expected 23:30 but got 22:30

Most of the time it works okay on the retry.  Any ideas or suggestion on how to fix it would be really helpfull.

**Comment by HasseM** [comment]
It seems that adding a small delay in def __time_picker, after clicking the time_picker gives huge improvements on this. I asume that my PC is too fast and already clicks the option before they are all opened/shown or something like that.

**Comment by wkaisertexas** [comment]
Duly noted. I will be adding this in the next major revision. 

Thanks so much for the input.

**Comment by XavierZambrano** [comment]
https://github.com/wkaisertexas/tiktok-uploader/issues/50

**Comment by lavanphat** [comment]
i have same error but with month. i'm using python 3.8.10
```
Failed to set schedule: time data 'November' does not match format '%B'
[17:28:33] Failed to set schedule: time data 'November' does not match format '%B'
```

**Comment by Mo-to** [comment]
I fixed this issue by changing:
https://github.com/wkaisertexas/tiktok-uploader/blob/31c23571613ee1ebb91b1fa018c46e8724211509/src/tiktok_uploader/upload.py#L560

To
```
time.sleep(1)  # wait for the DOM change
```

Waiting for 1 sec. instead of 0.5 seems to be enough at least for my PC.

**Comment by wkaisertexas** [comment]
Will change. Probably will go over with explicit waits because some people have slow connections / computers and selenium slows down browsers a ton.
