### ISSUE TITLE
i can't use it

### ISSUE THREAD

**Issue by qweaeqew** [wkaisertexas/tiktok-uploader#6]
i type
`tiktok-uploader \ -v video.mp4 \ -c cookies.txt`
and recieve
`usage: tiktok-uploader [-h] -v VIDEO [-d DESCRIPTION] [-c COOKIES] [-u USERNAME] [-p PASSWORD] [--headless]
tiktok-uploader: error: unrecognized arguments: \ \`

**Comment by wkaisertexas** [comment]
Slashes in CLI commands allow you to place the commands on multiple lines. This was something that I did to make the README easier to read. 

However, it seems like the command copied wrong and you should just use the command

```console
tiktok-uplodaer -v video.mp4 -c cookies.txt
```
