### ISSUE TITLE
Tried to upload multiple videos, the first one worked, the second one returned an error.

### ISSUE THREAD

**Issue by xingheyiyi** [wkaisertexas/tiktok-uploader#64]
[10:56:13] Posting C:\Users\Administrator\Desktop\视频\1.mp4
               with description: @magoxh @magoxh @magoxh 
[10:56:13] Navigating to upload page
[10:56:13] Failed to upload C:\Users\Administrator\Desktop\视频\1.mp4
[10:56:13] Alert Text: {Alert text : 
Message: unexpected alert open: {Alert text : }
  (Session info: chrome=117.0.5938.150)
Stacktrace:
	GetHandleVerifier [0x00DDCFE3+45267]
	(No symbol) [0x00D69741]
	(No symbol) [0x00C5BE1D]
	(No symbol) [0x00CBE2AD]
	(No symbol) [0x00CAAE36]
	(No symbol) [0x00C8674E]
	(No symbol) [0x00C878ED]
	GetHandleVerifier [0x01095659+2897737]
	GetHandleVerifier [0x010DE78B+3197051]
	GetHandleVerifier [0x010D8571+3171937]
	GetHandleVerifier [0x00E65E40+606000]
	(No symbol) [0x00D7338C]
	(No symbol) [0x00D6F508]
	(No symbol) [0x00D6F62F]
	(No symbol) [0x00D61D27]
	BaseThreadInitThunk [0x7551FCC9+25]
	RtlGetAppContainerNamedObjectPath [0x770E7B1E+286]
	RtlGetAppContainerNamedObjectPath [0x770E7AEE+238]

C:\Users\Administrator\Desktop\视频\1.mp4 with description "@magoxh @magoxh @magoxh " failed

**Comment by NVT100** [comment]
Have you fixed this yet?

**Comment by wkaisertexas** [comment]
@misterno thanks so much for the PR. Should be merged now
