### ISSUE TITLE
 No module named 'tiktok_uploader'

### ISSUE THREAD

**Issue by tryykimies** [wkaisertexas/tiktok-uploader#67]
i am getting this error:
    from tiktok_uploader.upload import upload_video, upload_videos
ModuleNotFoundError: No module named 'tiktok_uploader'

Every other module in my project works fine, first tine using tiktok-uploader, installed everything via pip, anyone else have/had this problem? thanks in advance

**Comment by wkaisertexas** [comment]
Did you install it via 'pip install tiktok-uploader'?

I don't know what would case that issue otherwise. I just tried installing and importing from a clean Python install. Everything worked fine, so I am not sure of the issue.

**Comment by tryykimies** [comment]
yeah, pip install tiktok-uploader, I also installed this
git clone https://github.com/wkaisertexas/tiktok-uploader.git
cd tiktok-uploader
pip install hatch
hatch build
pip install -e .

**Comment by YoussefBechara** [comment]
bro you have to rename tiktok-uploader files to tiktok_uploader and modify the import tiktok_uploader to tiktok_uploader.src.tiktok_uploader.utils for example
