### ISSUE TITLE
How to add music from Tiktok to video when upload ?

### ISSUE THREAD

**Issue by impec0762** [wkaisertexas/tiktok-uploader#72]
Hi. This is a great tool to automatically upload videos to tiktok. Can you provide more functionality to add music on Tiktok to videos ?
Feature is added now on TikTok web portal
Please update

**Comment by wkaisertexas** [comment]
No. Music is relatively easy to add to a video programmatically (see `ffmpeg`). Internationalization is a big issue for this repository as creator center is not available for much of the world. 

Furthermore, sound names are not unique. Building a potentially non-deterministic result for selecting community created sounds is not the intended vision for this library.

Finally, it would take quite a bit of time (`@` and `#` took me forever to get working and test).

**Comment by impec0762** [comment]
My goal is to add the same unique sound through the process which is as
follows:

Maybe you could be kind by helping me with this custom customization that
I'm trying to do, I don't really know how to do it but I know that the
changes should be inserted in the Config file.toml 🙏🏽

- Click on the “Edit video” button
- Enter the title and the name of the artist in the music search bar Ex:
“Music Artist Name”
- Click on the “Finish” button
- Select the first result at the top of the list by clicking on the “Use
this” button
- Click on the “Save the modification” button

... Continue the rest of the process of uploading the video

Le jeu. 16 nov. 2023 à 23:13, William Kaiser ***@***.***> a
écrit :

**Comment by wkaisertexas** [comment]
I know the general process and I have looked at the form. But what music by
that artist changes and the most popular song for a particular keyword
changes.

All in all, this is a lot of work to deal with and could potentially break
things. Maybe after the creator center gets published worldwide. However,
not at this current moment.

**Comment by impec0762** [comment]
Sorry to insist, I completely understand your point of view and I
especially don't want to waste your time because I know how precious it is.

But this is a favor that I am asking you because the need for this feature
for my activity is much too great.

I beg you to take a look at my concern with a kind heart.

I understand that this could require a lot of work but by just giving me a
few leads such as the names of selectors, Elements or Classes that I should
add here and there in the code, or just a beginning of a lead, it would
help me a lot.

I will be eternally grateful to you for this

I understand that the sound may vary depending on the keyword and at any
time but please help me, it's really important, please, even if you prefer
to give me a private answer, I will gladly accept it, big brother!

Le ven. 17 nov. 2023 à 00:07, William Kaiser ***@***.***> a
écrit :

> I know the general process and I have looked at the form. But what music
> by
> that artist changes and the most popular song for a particular keyword
> changes.
>
> All in all, this is a lot of work to deal with and could potentially break
> things. Maybe after the creator center gets published worldwide. However,
> not at this current moment.
>

**Comment by wkaisertexas** [comment]
You could always fork the library yourself and add the feature.

**Comment by impec0762** [comment]
All right
Why no proxy seems to work with the script?

Le ven. 17 nov. 2023 à 02:12, William Kaiser ***@***.***> a
écrit :

> You could always fork the library yourself and add the feature.
>

**Comment by wkaisertexas** [comment]
Could I maybe have a bit more information about your proxy setup?

Hard to diagnose issues without context.

**Comment by impec0762** [comment]
I'm using 922 S5 proxy 
I added the proxy in the port settings on VS code

My command line:

proxy = {'host': '185.229.225.77', 'port': '30000'}
upload_video('#_##misiuneatiktok_.mp4', '#fyp #twerk #twerktwerktwerk #twerkcompilations', 'cookies.txt', headless=True, proxy=proxy)

**Comment by impec0762** [comment]
I found the way to add the music, I tested it and it works perfectly!
Can we discuss by email in private?

Le ven. 17 nov. 2023 à 11:51, William Kaiser ***@***.***> a
écrit :

> Could I maybe have a bit more information about your proxy setup?
>
> Hard to diagnose issues without context.
>

**Comment by wkaisertexas** [comment]
Submit a pull request if it works for you and I can review it.

**Comment by impec0762** [comment]
I can't create a pull request because I need to be a collaborator. We need to change or adjust Xpath because in some case this not work: 

`# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re

class AddMusic2(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Chrome(executable_path=r'')
        self.driver.implicitly_wait(30)
        self.base_url = "https://www.google.com/"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_add_music2(self):
        driver = self.driver
        driver.get("https://www.tiktok.com/creator-center/upload?from=upload&lang=en")
        #ERROR: Caught exception [ERROR: Unsupported command [selectFrame | index=0 | ]]
        driver.find_element_by_xpath("//div[@id='root']/div/div/div/div/div/div[2]/button/div/div").click()
        driver.find_element_by_xpath("//div[@id='tux-portal-container']/div[2]/div/div/div/div/div[2]/div/div[3]/div/div[2]/div/div").click()
        driver.find_element_by_xpath("//input[@value='Zmoneeey Go dumb get stupid']").clear()
        driver.find_element_by_xpath("//input[@value='Zmoneeey Go dumb get stupid']").send_keys("Zmoneeey Go dumb get stupid")
        driver.find_element_by_xpath("//input[@value='Zmoneeey Go dumb get stupid']").send_keys(Keys.ENTER)
        driver.find_element_by_xpath("//div[@id='tux-portal-container']/div[2]/div/div/div/div/div[2]/div/div[3]/div/div[2]/div/div[2]/div/div/div/div/div[2]/button/div/div").click()
        driver.find_element_by_xpath("//div[@id='tux-portal-container']/div[2]/div/div/div/div/div[2]/div/div/span/div/div[2]/button[2]/div/div").click()
    
    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException as e: return False
        return True
    
    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException as e: return False
        return True
    
    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
`

**Comment by wkaisertexas** [comment]
Creating a pull request is how you become a collaborator. Anyone can do it
on the repository..

If it doesn’t work reliably that is an issue…
