### ISSUE TITLE
Reuse your Tiktok logged in browser instead of logging in to a new browser every time you post a video

### ISSUE THREAD

**Issue by lavanphat** [wkaisertexas/tiktok-uploader#75]
Can I reuse my logged in browser to post videos? I don't want a new login every time I run the code

**Comment by wkaisertexas** [comment]
Yes. Your cookies are how your login state is kept (ie: the keep me signed in button), so you should have your cookies be valid as long as you would normally be signed into your browser

**Comment by albertxu1** [comment]
So, when driving a antidetect browser instance which has my tiktok account logined, do I still have to copy the cookies to use this uploader?
