### ISSUE TITLE
Schedule fails when set month

### ISSUE THREAD

**Issue by lavanphat** [wkaisertexas/tiktok-uploader#76]
i receive a error when set schedule. i'm using python 3.8.10

This is log error 
```
Failed to set schedule: time data 'November' does not match format '%B'
[17:28:33] Failed to set schedule: time data 'November' does not match format '%B'
```

**Comment by wkaisertexas** [comment]
Honestly, using a cron job would probably be easier

**Comment by Skyslycer** [comment]
> Honestly, using a cron job would probably be easier

Scheduling has it's uses, I can't get it to work right now tho sadly. #75
