### ISSUE TITLE
update link for upload

### ISSUE THREAD

**Issue by DxnielKS** [wkaisertexas/tiktok-uploader#78]
Please update the link to upload.
```driver.get('https://www.tiktok.com/upload?lang=en')```

**Comment by wkaisertexas** [comment]
Can you provide a bit more context about your issue? Are you having issues with creator center? Is the script failing? Can you provide additional information about your issue?

**Comment by DxnielKS** [comment]
When navigating to the upload section. It's using a different url and the script is failing.
