### ISSUE TITLE
Tiktok is renovating to a new interface, more detail below

### ISSUE THREAD

**Issue by zegeree** [wkaisertexas/tiktok-uploader#82]
A change in interface which causes the script to fail,

for: def _set_video(driver, path: str = '', num_retries: int = 3, **kwargs) -> None:

in upload.py

interface of

            # wait until a non-draggable image is found
            process_confirmation = EC.presence_of_element_located(
                (By.XPATH, config['selectors']['upload']['process_confirmation'])
                )
            WebDriverWait(driver, config['explicit_wait']).until(process_confirmation)
            
has been changed which causes the script to not continue

![Screenshot 2023-12-11 181524](https://github.com/wkaisertexas/tiktok-uploader/assets/60013138/470aeca9-7a3f-4df1-aa2a-9a9e925256ab)

as you can see in the screenshots this way of setting the thumbnail,cover of the video has been changed

Made a temp fix for this by implementing a waiting time for this step. Would be nice if we can get an actual fix for this

**Comment by alexcreanga-dev** [comment]
Does the video actually uploads to tiktok? For me the error comes even before it is selected into the uploading section

**Comment by zegeree** [comment]
> Does the video actually uploads to tiktok? For me the error comes even before it is selected into the uploading section

ye everything works fine for me, could you give me the error message that your getting? Might be abled to help

**Comment by zegeree** [comment]
> Does the video actually uploads to tiktok? For me the error comes even before it is selected into the uploading section

Yes, everything works fine appart from this new change tiktok made, which i fixed by implementing a temporarily fix.

**Comment by TheLime1** [comment]
@zegeree can you PR you fix ?

**Comment by zegeree** [comment]
> @zegeree can you PR you fix ?

I cant change, I dont have the skills either on this level. They'll look at it soon

**Comment by MarshmallowB** [comment]
@zegeree can you pls share the fix? :')

**Comment by muhammad-anser** [comment]
I am also facing the same issue.

**Comment by devQA-0007** [comment]
Do you Already Know ehen we can expect a Solution ? TikTop has now completly changed the Design

**Comment by wkaisertexas** [comment]
I am on Apple Silicon and the webdriver does not work for me. I can not really debug the application anymore. Sorry you all.

**Comment by devQA-0007** [comment]
Does this mean that the API is no longer being developed?
