### ISSUE TITLE
[VERY FAST IDEA]: Skip `_remove_split_window` function

### ISSUE THREAD

**Issue by SinnnwL** [wkaisertexas/tiktok-uploader#83]
Each time I am uploading, I come across this messages
```
[19:54:09] Removing split window
[19:54:14] Split window not found or operation timed out
```
In fact, it seems that I don't really need the `_remove_split_window` function because the split window is never opened on my case.
So is it possible to add optional boolean args called `skip_remove_split_window` in the `upload_videos` that is by default set to false ?

**Comment by wkaisertexas** [comment]
The '_remove_split_window' function was added because TikTok was pushing that a few months ago.  I need to look into fixing this or making this fail gracefully.
