### ISSUE TITLE
Add OperaDriver Selenium support

### ISSUE THREAD

**Issue by MatteoFasulo** [wkaisertexas/tiktok-uploader#86]
Hello,

I'm interested in the possibility of incorporating the OperaDriver for Selenium, which is based on Chromium (https://github.com/operasoftware/operachromiumdriver).

Anticipating your response.

**Comment by wkaisertexas** [comment]
Probably not by default. Why don't you just use Chrome or FireFox for the automation script?

I do not want to have to support extra browsers which could break over time.
