### ISSUE TITLE
Message:  Stacktrace: 0   chromedriver

### ISSUE THREAD

**Issue by Zeffut** [wkaisertexas/tiktok-uploader#88]
Message: 
Stacktrace:
0   chromedriver                        0x0000000100e184dc chromedriver + 4162780
1   chromedriver                        0x0000000100e10664 chromedriver + 4130404
2   chromedriver                        0x0000000100a67bc0 chromedriver + 293824
3   chromedriver                        0x0000000100aae040 chromedriver + 581696
4   chromedriver                        0x0000000100aedab0 chromedriver + 842416
5   chromedriver                        0x0000000100aa16bc chromedriver + 530108
6   chromedriver                        0x0000000100aa2930 chromedriver + 534832
7   chromedriver                        0x0000000100ddde08 chromedriver + 3923464
8   chromedriver                        0x0000000100de23dc chromedriver + 3941340
9   chromedriver                        0x0000000100dc6038 chromedriver + 3825720
10  chromedriver                        0x0000000100de2f3c chromedriver + 3944252
11  chromedriver                        0x0000000100db86f4 chromedriver + 3770100
12  chromedriver                        0x0000000100dff980 chromedriver + 4061568
13  chromedriver                        0x0000000100dffaf8 chromedriver + 4061944
14  chromedriver                        0x0000000100e102e4 chromedriver + 4129508
15  libsystem_pthread.dylib             0x000000018c456034 _pthread_start + 136
16  libsystem_pthread.dylib             0x000000018c450e3c thread_start + 8

**Comment by wkaisertexas** [comment]
Okay, can you post a little bit more information about your issue. Printing a stack-trace is not exactly helpful

**Comment by Zeffut** [comment]
All I saw was this error message and I don't understand why the code manages to click on some buttons but not the "Publish" one.

**Comment by Zeffut** [comment]
I just saw that it works on Windows 11 but not MacOS

**Comment by wkaisertexas** [comment]
It doesn't work on macOS arm (for the new Apple Silicon chips) at least. The gecko driver is not working which is annoying.
