### ISSUE TITLE
Correct time schedule check failing consistenly

### ISSUE THREAD

**Issue by gagewillette** [wkaisertexas/tiktok-uploader#90]
Been having some issues with the check the runs to ensure that the schedule is correct before the upload button is clicked.

![image](https://github.com/wkaisertexas/tiktok-uploader/assets/79120652/e166a4be-e773-4d97-a362-5abff621107a)

Something I have found is that the schedule usually never works with odd hour numbers (this could be superstitious but that is what I have noticed).

I forked the repo and have been trying to find a fix but still nothing yet, figured I would put this out there.

Lmk with any questions

**Comment by romanrsr** [comment]
Same here

**Comment by LyesStockly** [comment]
But 18:00 is not a odd number ? Did you mean even ?

**Comment by gagewillette** [comment]
@LyesStockly No I meant odd sorry for the confusion. I was trying to say that it fails CONSISTENTLY with ODD numbers, but i have found that its mostly 50/50 with the even numbers. Also, I haven't tested this that much so take what I say with a grain of salt, but when it says for instance it found 18:05, if I were to rerun the program and set the schedule time to 18:05, it works (again I haven't tested this a whole lot)

**Comment by wkaisertexas** [comment]
I need to dive deeper into how the scheduler works. If TikTok had the schedule feature, I probably would not have made this module. Honestly, I intended for basic 'cron' jobs to schedule posts, but scheduling through TikTok itself is definitely better.
