### ISSUE TITLE
Failed to upload Video

### ISSUE THREAD

**Issue by romanrsr** [wkaisertexas/tiktok-uploader#95]
`[00:40:12] ←[92mAuthenticating browser with cookies←[0m [00:40:12] Create a firefox browser instance [00:40:53] Authenticating browser with cookies [00:40:56] Posting C:\Users\Administrator\Desktop\tiktok-uploader\tiktok-uploader\video.mp4 with description: This is a video I just downloaded [00:40:56] Navigating to upload page [00:40:58] Uploading video file [00:41:03] Removing split window [00:41:08] Split window not found or operation timed out [00:41:08] Setting interactivity settings [00:41:10] Setting description [00:41:11] Clicking the post button [00:42:12] Failed to upload C:\Users\Administrator\Desktop\tiktok-uploader\tiktok-uploader\video.mp4 [00:42:12] Message: Stacktrace: RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8 WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:189:5 NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:507:5 dom.find/</<@chrome://remote/content/shared/DOM.sys.mjs:132:16`

**Comment by gavink97** [comment]
This issue is addressed in my PR #87 which is awaiting confirmation ☺️. Feel free to build from my fork in the meantime.

**Comment by TheIndependentBrotherhood** [comment]
Hi!
I have exactly the same problem, but when I look without Headless, the proccess goes all the way through without a hitch.
I switch back to manual mode and no problem, successful upload.

**Comment by TheIndependentBrotherhood** [comment]
> > This issue is addressed in my PR #87 which is awaiting confirmation ☺️. Feel free to build from my fork in the meantime.
> 
> Thank you! I have built from your fork, but now the problem I have is that although it says "Video posted successfully", then the video does not appear posted.

Hi!
I have exactly the same problem, but when I look without Headless, the proccess goes all the way through without a hitch.
I switch back to manual mode and no problem, successful upload.

**Comment by romanrsr** [comment]
> > > This issue is addressed in my PR #87 which is awaiting confirmation ☺️. Feel free to build from my fork in the meantime.
> > 
> > 
> > Thank you! I have built from your fork, but now the problem I have is that although it says "Video posted successfully", then the video does not appear posted.
> 
> Hi! I have exactly the same problem, but when I look without Headless, the proccess goes all the way through without a hitch. I switch back to manual mode and no problem, successful upload.

Are you by chance using more than one Tiktok account?

**Comment by gavink97** [comment]
If its completing the script and the video isn't posted I wouldn't know what the solution would be.

Try taking some screenshots with the driver before it clicks the post button and when it clicks the post confirmation. 

If it finished uploading and makes it to the post page but the video is missing TikTok might have blocked your account from uploading videos for the day.

I had the same error happen to me when I was testing but after a day all of my uploads were posting.

**Comment by TheIndependentBrotherhood** [comment]
> > > > This issue is addressed in my PR #87 which is awaiting confirmation ☺️. Feel free to build from my fork in the meantime.
> > > 
> > > 
> > > Thank you! I have built from your fork, but now the problem I have is that although it says "Video posted successfully", then the video does not appear posted.
> > 
> > 
> > Hi! I have exactly the same problem, but when I look without Headless, the proccess goes all the way through without a hitch. I switch back to manual mode and no problem, successful upload.
> 
> Are you by chance using more than one Tiktok account?

Sorry, just one account

**Comment by TheIndependentBrotherhood** [comment]
> If its completing the script and the video isn't posted I wouldn't know what the solution would be.
> 
> Try taking some screenshots with the driver before it clicks the post button and when it clicks the post confirmation.
> 
> If it finished uploading and makes it to the post page but the video is missing TikTok might have blocked your account from uploading videos for the day.
> 
> I had the same error happen to me when I was testing but after a day all of my uploads were posting.

Yes, I had already seen this error, and it seems to me that you could catcher the error, because I thought I saw a very specific server response in this case.

But since I can upload without any problem by doing it manually, without waiting, it's weird.

**Comment by TheIndependentBrotherhood** [comment]
Now I have the "Manage your posts" publication confirmation button ... :)

**Comment by gavink97** [comment]
> Yes, I had already seen this error, and it seems to me that you could catcher the error, because I thought I saw a very specific server response in this case.

If you thought you saw something you should look into it 😄 you probably know more about the codebase than I do. My PR was just meant to adjust the post confirmation because TikTok has been updating their UI.

**Comment by brainwashing-enjoyer** [comment]
I have the same problem. I use Firefox, If I try to run the script with Chrome as the browser it just results in a stacktrace error. I also run Linux as my OS; that could be something to do with it.

**Comment by brainwashing-enjoyer** [comment]
It could be the case that Tiktok has implemented new measures to stop automatic publishing. If so, what can we do?

**Comment by SinnnwL** [comment]
```
# wait until a non-draggable image is found
#process_confirmation = EC.presence_of_element_located((By.XPATH, config['selectors']['upload']['process_confirmation']))
#WebDriverWait(driver, config['explicit_wait']).until(process_confirmation)
```
  
            
Do we know what this part of the code is for ?
