### ISSUE TITLE
Error when uploading

### ISSUE THREAD

**Issue by Zeffut** [wkaisertexas/tiktok-uploader#99]
I got this error but i don't know why :

[18:42:09] Navigating to upload page
[18:42:12] Uploading video file
Message: 
Stacktrace:
0   chromedriver                        0x0000000102c584dc chromedriver + 4162780
1   chromedriver                        0x0000000102c50664 chromedriver + 4130404
2   chromedriver                        0x00000001028a7bc0 chromedriver + 293824
3   chromedriver                        0x00000001028ee040 chromedriver + 581696
4   chromedriver                        0x000000010292dab0 chromedriver + 842416
5   chromedriver                        0x00000001028e16bc chromedriver + 530108
6   chromedriver                        0x00000001028e2930 chromedriver + 534832
7   chromedriver                        0x0000000102c1de08 chromedriver + 3923464
8   chromedriver                        0x0000000102c223dc chromedriver + 3941340
9   chromedriver                        0x0000000102c06038 chromedriver + 3825720
10  chromedriver                        0x0000000102c22f3c chromedriver + 3944252
11  chromedriver                        0x0000000102bf86f4 chromedriver + 3770100
12  chromedriver                        0x0000000102c3f980 chromedriver + 4061568
13  chromedriver                        0x0000000102c3faf8 chromedriver + 4061944
14  chromedriver                        0x0000000102c502e4 chromedriver + 4129508
15  libsystem_pthread.dylib             0x00000001874ba034 _pthread_start + 136
16  libsystem_pthread.dylib             0x00000001874b4e3c thread_start + 8

**Comment by thaithanhdhv** [comment]
I got the same problem

**Comment by ArdiGG** [comment]
+

**Comment by byStayo** [comment]
same
